import { StyleSheet } from "react-native";
import { BrandColors, Typography, Spacing, BorderRadius } from "../../../../../shared/theme";

export const styles = StyleSheet.create({
  container: {
    paddingBottom: Spacing.xl,
  },
  summaryCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.md,
    padding: Spacing.base,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginBottom: Spacing.md,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: Spacing.sm,
    paddingBottom: Spacing.xs,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  cardHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  cardTitle: {
    fontSize: Typography.fontSize.base,
    fontWeight: "700",
    color: "#0F172A",
  },
  editAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 2,
    paddingHorizontal: 6,
  },
  editText: {
    fontSize: Typography.fontSize.xs,
    fontWeight: "700",
    color: BrandColors.PRIMARY_ORANGE_DARK || "#EA580C",
  },
  readOnlyGrid: {
    gap: 8,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 2,
  },
  label: {
    fontSize: Typography.fontSize.xs,
    color: "#64748B",
  },
  value: {
    fontSize: Typography.fontSize.xs,
    fontWeight: "600",
    color: "#0F172A",
    textAlign: "right",
    flexShrink: 1,
  },
  highlightValue: {
    fontSize: Typography.fontSize.sm,
    fontWeight: "700",
    color: BrandColors.PRIMARY_ORANGE_DARK || "#EA580C",
  },
  // Structured Document List in Review
  docsList: {
    gap: 8,
    marginTop: 4,
  },
  docRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: BorderRadius.sm,
    padding: 10,
  },
  docRowLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
    marginRight: 8,
  },
  docIconCircle: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: "#DCFCE7",
    alignItems: "center",
    justifyContent: "center",
  },
  docMetaCol: {
    flex: 1,
  },
  docTitle: {
    fontSize: Typography.fontSize.xs,
    fontWeight: "700",
    color: "#0F172A",
  },
  docSub: {
    fontSize: 11,
    color: "#166534",
    marginTop: 2,
    fontWeight: "500",
  },
  previewBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: BrandColors.PRIMARY_ORANGE || "#EA580C",
    backgroundColor: "#FEF0E6",
  },
  previewBtnText: {
    fontSize: 11,
    fontWeight: "700",
    color: BrandColors.PRIMARY_ORANGE_DARK || "#EA580C",
  },
  consentContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.md,
    padding: Spacing.base,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginTop: 4,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: "#CBD5E1",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    marginTop: 2,
    backgroundColor: "#FFFFFF",
  },
  checkboxActive: {
    backgroundColor: BrandColors.PRIMARY_ORANGE || "#EA580C",
    borderColor: BrandColors.PRIMARY_ORANGE || "#EA580C",
  },
  consentText: {
    flex: 1,
    fontSize: Typography.fontSize.xs,
    color: "#475569",
    lineHeight: 18,
  },
});
