/**
 * Screen: GST Cancellation (Styles & Constants)
 * Reuses GST Amendment design tokens. Strictly under 300 lines.
 */
import { StyleSheet, Platform } from "react-native";
import {
  BrandColors,
  BorderRadius,
  BorderWidth,
  Spacing,
  Typography,
} from "@/shared/theme";

export const CANCELLATION_REASONS = [
  "Discontinuance / Closure of Business",
  "Annual Turnover Fell Below GST Exemption Limit (₹40L/₹20L)",
  "Transfer of Business / Demerger / Amalgamation",
  "Death of Sole Proprietor",
  "Change in Legal Constitution",
  "Other Valid Reason",
];

export const ACCEPTED_PROOFS = [
  "Business Closure Proof",
  "Sale / Transfer Agreement",
  "Merger / Amalgamation Document",
  "Revised Constitution / Partnership Document",
  "Death Certificate",
  "Other Relevant Supporting Document",
];

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: BrandColors.WHITE },
  headerBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: Spacing.base,
    paddingBottom: 12,
    backgroundColor: BrandColors.WHITE,
  },
  backButton: {
    width: 38,
    height: 38,
    justifyContent: "center",
    alignItems: "center",
  },
  roundBackButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#F1F5F9",
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitleWrap: { alignItems: "center" },
  headerTitle: {
    fontSize: Typography.fontSize.xl,
    fontWeight: Typography.fontWeight.bold,
    color: BrandColors.TEXT_PRIMARY,
    fontFamily: Platform.select({
      ios: "System",
      android: "sans-serif-medium",
    }),
  },
  headerMainTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: BrandColors.TEXT_PRIMARY,
  },
  headerSubtitle: {
    fontSize: 12,
    color: "#64748B",
    marginTop: 2,
    fontWeight: "500",
  },
  placeholderBox: { width: 38 },
  scrollView: { flex: 1 },
  scrollContent: { padding: Spacing.base, paddingBottom: 40, gap: 14 },

  /* Form Elements */
  formSectionTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0F172A",
    marginTop: 4,
    marginBottom: -4,
  },
  fieldGroup: { gap: 6 },
  label: {
    fontSize: Typography.fontSize.sm + 1,
    fontWeight: Typography.fontWeight.semiBold,
    color: BrandColors.TEXT_PRIMARY,
  },
  star: { color: "#EF4444" },
  input: {
    height: 48,
    backgroundColor: BrandColors.BACKGROUND,
    borderRadius: BorderRadius.md,
    borderWidth: BorderWidth.thin,
    borderColor: "#E2E8F0",
    paddingHorizontal: 14,
    fontSize: Typography.fontSize.base,
    color: BrandColors.TEXT_PRIMARY,
  },
  textArea: {
    minHeight: 88,
    backgroundColor: BrandColors.WHITE,
    borderRadius: BorderRadius.md,
    borderWidth: BorderWidth.thin,
    borderColor: "#E2E8F0",
    padding: 12,
    fontSize: Typography.fontSize.sm + 1.5,
    color: BrandColors.TEXT_PRIMARY,
    textAlignVertical: "top",
  },
  counterRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  charCount: { fontSize: Typography.fontSize.xs + 1, color: "#94A3B8" },
  selectBox: {
    height: 48,
    backgroundColor: BrandColors.WHITE,
    borderRadius: BorderRadius.md,
    borderWidth: BorderWidth.thin,
    borderColor: "#E2E8F0",
    paddingHorizontal: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  selectText: {
    fontSize: Typography.fontSize.base,
    fontWeight: Typography.fontWeight.semiBold,
    color: BrandColors.TEXT_PRIMARY,
  },
  placeholderText: {
    color: "#94A3B8",
    fontWeight: Typography.fontWeight.regular,
  },
  declarationRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingVertical: 4,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: "#94A3B8",
    backgroundColor: BrandColors.WHITE,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 2,
  },
  checkboxActive: {
    backgroundColor: BrandColors.PRIMARY_ORANGE,
    borderColor: BrandColors.PRIMARY_ORANGE,
  },
  declarationLabel: {
    fontSize: Typography.fontSize.xs + 2.5,
    fontWeight: Typography.fontWeight.semiBold,
    color: BrandColors.TEXT_PRIMARY,
  },
  declarationSubText: {
    fontSize: Typography.fontSize.xs + 1.5,
    color: BrandColors.TEXT_SECONDARY,
    marginTop: 1,
  },
  inputError: { borderColor: "#EF4444", backgroundColor: "#FEF2F2" },
  errorText: {
    fontSize: Typography.fontSize.xs + 1.5,
    color: "#DC2626",
    fontWeight: Typography.fontWeight.medium,
  },

  /* Supporting Proof Card (Exact Match to Screenshot) */
  proofCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: 16,
    gap: 14,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  proofDescText: { fontSize: 13.5, color: "#64748B", lineHeight: 20 },
  uploadActionsRow: { flexDirection: "row", gap: 12 },
  uploadBtn: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#083B75",
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  uploadBtnText: { fontSize: 14, fontWeight: "700", color: "#083B75" },
  docPreviewRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: 12,
  },
  docPreviewIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: "#EAF1FE",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  docPreviewInfo: { flex: 1, marginRight: 12, overflow: "hidden" },
  docPreviewName: { fontSize: 13.5, fontWeight: "700", color: "#0F172A" },
  docPreviewSize: { fontSize: 11.5, color: "#64748B", marginTop: 2 },
  docDeleteBtn: { paddingHorizontal: 8, paddingVertical: 4 },
  docDeleteText: { fontSize: 13, fontWeight: "700", color: "#DC2626" },

  /* Accepted Proofs Card (Exact Match to Screenshot) */
  acceptedProofsCard: {
    backgroundColor: "#FFF7ED",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#FFEDD5",
    padding: 16,
    marginTop: 2,
  },
  acceptedProofsHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    gap: 8,
  },
  acceptedProofsTitle: { fontSize: 15, fontWeight: "700", color: "#0F172A" },
  acceptedProofList: { marginTop: 2 },
  acceptedProofItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 8,
    paddingRight: 4,
  },
  acceptedProofBullet: {
    fontSize: 14,
    color: "#334155",
    marginRight: 8,
    lineHeight: 20,
  },
  acceptedProofText: {
    flex: 1,
    fontSize: 13.5,
    color: "#334155",
    lineHeight: 20,
    fontWeight: "400",
  },
  viewMoreBtn: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-end",
    marginTop: 4,
    paddingVertical: 4,
    paddingHorizontal: 2,
    gap: 4,
  },
  viewMoreText: {
    fontSize: 13,
    fontWeight: "700",
    color: BrandColors.PRIMARY_ORANGE,
  },

  /* Buttons */
  actionOrangeBtn: {
    height: 52,
    borderRadius: 26,
    backgroundColor: BrandColors.PRIMARY_ORANGE,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: BrandColors.PRIMARY_ORANGE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 3,
    marginTop: Spacing.sm,
  },
  actionOrangeBtnText: {
    fontSize: Typography.fontSize.md,
    fontWeight: Typography.fontWeight.bold,
    color: BrandColors.WHITE,
  },
  primaryBtn: {
    height: 50,
    borderRadius: 25,
    backgroundColor: BrandColors.PRIMARY_ORANGE,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: BrandColors.PRIMARY_ORANGE,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 2,
  },
  primaryBtnText: { fontSize: 15, fontWeight: "700", color: BrandColors.WHITE },
  secondaryBtn: {
    height: 50,
    borderRadius: 25,
    backgroundColor: "#F1F5F9",
    justifyContent: "center",
    alignItems: "center",
  },
  secondaryBtnText: { fontSize: 15, fontWeight: "700", color: "#083B75" },
  bottomBar: {
    paddingHorizontal: Spacing.base,
    paddingTop: 12,
    backgroundColor: BrandColors.WHITE,
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
  },

  /* Review Screen Cards */
  reviewCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.lg,
    padding: Spacing.base,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    gap: 12,
  },
  reviewCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  reviewCardTitle: { fontSize: 15, fontWeight: "700", color: "#083B75" },
  reviewRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingVertical: 2,
  },
  reviewKey: { fontSize: 13, color: "#64748B", flex: 1 },
  reviewVal: {
    fontSize: 13,
    fontWeight: "600",
    color: BrandColors.TEXT_PRIMARY,
    flex: 1.4,
    textAlign: "right",
  },
  reviewDivider: { height: 1, backgroundColor: "#F1F5F9" },
  reviewDeclarationBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    backgroundColor: "#F8FAFC",
    padding: 14,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  reviewDeclarationText: {
    flex: 1,
    fontSize: 12.5,
    color: BrandColors.TEXT_PRIMARY,
    lineHeight: 18,
    fontWeight: "500",
  },

  /* Success Screen */
  successContainer: { flex: 1, backgroundColor: "#F8FAFC" },
  successHero: {
    backgroundColor: BrandColors.PRIMARY_BLUE,
    paddingHorizontal: 24,
    paddingBottom: 40,
    alignItems: "center",
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  successHeroIconBox: { marginBottom: 16 },
  successHeroCheckCircle: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: "#16A34A",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#16A34A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 4,
  },
  successHeroTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#FFFFFF",
    textAlign: "center",
  },
  successHeroSubtitle: {
    fontSize: 13,
    color: "#94A3B8",
    textAlign: "center",
    marginTop: 6,
    lineHeight: 18,
  },
  successCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    marginHorizontal: 16,
    marginTop: -20,
    padding: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 4,
    gap: 10,
  },
  successRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 3,
  },
  successRowKey: { fontSize: 13, color: "#64748B" },
  successRowVal: {
    fontSize: 13,
    fontWeight: "700",
    color: BrandColors.TEXT_PRIMARY,
  },
  successDivider: { height: 1, backgroundColor: "#F1F5F9" },
  successActionsWrap: {
    paddingHorizontal: 16,
    paddingTop: 16,
    backgroundColor: "#F8FAFC",
    gap: 10,
  },
});
