export const BrandColors = {
  PRIMARY_BLUE: "#083B75",
  PRIMARY_BLUE_DARK: "#06152D",
  PRIMARY_BLUE_ACCENT: "#0B5ED7",
  PRIMARY_LIGHT_BLUE: "#EAF1FE",
  PRIMARY_ORANGE: "#FF7A00",
  PRIMARY_ORANGE_DARK: "#EA580C",
  PRIMARY_LIGHT_ORANGE: "#FEF0E6",
  BACKGROUND: "#F8FAFC",
  CARD: "#FFFFFF",
  CARD_BORDER: "#F1F5F9",
  TEXT_PRIMARY: "#0F172A",
  TEXT_SECONDARY: "#64748B",
  TEXT_MUTED: "#94A3B8",
  BORDER: "#E2E8F0",
  CHEVRON_BLUE: "#083B75",
  WHITE: "#FFFFFF",
};

export const Colors = {
  primary: BrandColors.PRIMARY_BLUE_ACCENT,
  primaryDark: BrandColors.PRIMARY_BLUE,
  primaryNavy: BrandColors.PRIMARY_BLUE_DARK,
  primaryLight: BrandColors.PRIMARY_LIGHT_BLUE,
  accent: BrandColors.PRIMARY_ORANGE,
  accentLight: BrandColors.PRIMARY_LIGHT_ORANGE,
  orange: BrandColors.PRIMARY_ORANGE,
  orangeLight: BrandColors.PRIMARY_LIGHT_ORANGE,
  success: "#059669",
  successLight: "#E6F5F0",
  warning: BrandColors.PRIMARY_ORANGE,
  warningLight: BrandColors.PRIMARY_LIGHT_ORANGE,
  error: "#DC2626",
  errorLight: "#FDEBEB",
  info: BrandColors.PRIMARY_BLUE_ACCENT,
  infoLight: BrandColors.PRIMARY_LIGHT_BLUE,
  background: BrandColors.BACKGROUND,
  card: BrandColors.CARD,
  cardBorder: BrandColors.CARD_BORDER,
  text: BrandColors.TEXT_PRIMARY,
  textSecondary: BrandColors.TEXT_SECONDARY,
  textMuted: BrandColors.TEXT_MUTED,
  border: BrandColors.BORDER,
  iconBgLight: BrandColors.PRIMARY_LIGHT_BLUE,
  white: "#FFFFFF",
  ...BrandColors,
};

export default Colors;
