import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8FAFC" },
  headerArea: { marginBottom: 20 },
  scrollContent: { padding: 16 },
  title: { fontSize: 24, fontWeight: "bold", color: "#0F172A", marginBottom: 6 },
  subtitle: { fontSize: 14, color: "#64748B", lineHeight: 20 },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  cardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 16, borderBottomWidth: 1, borderBottomColor: "#F1F5F9", paddingBottom: 12 },
  cardTitle: { fontSize: 16, fontWeight: "700", color: "#0F172A" },
  editBtn: { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: "#FFF7ED", paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20 },
  editBtnText: { fontSize: 13, fontWeight: "600", color: "#F97316" },
  cardBody: { gap: 12 },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', borderBottomWidth: 1, borderBottomColor: "#F8FAFC", paddingBottom: 8 },
  label: { fontSize: 13, color: "#64748B", flex: 1 },
  value: { fontSize: 13, color: "#0F172A", fontWeight: "600", flex: 1, textAlign: 'right' },
  docRow: { flexDirection: "row", alignItems: "center", justifyContent: 'space-between', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: "#F1F5F9" },
  docTitle: { fontSize: 14, color: "#0F172A", fontWeight: '500' },
  docSubtitle: { fontSize: 12, color: "#64748B", marginTop: 2 },
  eyeBtn: { padding: 8, backgroundColor: "#F1F5F9", borderRadius: 8 },
  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#FFFFFF",
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
  },
  continueButton: {
    backgroundColor: "#F97316",
    borderRadius: 12,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  continueButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "bold" },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.9)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalCloseBtn: {
    position: "absolute",
    top: 50,
    right: 20,
    zIndex: 10,
    padding: 8,
  },
  previewImage: {
    width: "90%",
    height: "80%",
  },
});

