import { StyleSheet } from "react-native";
import { BrandColors, Typography, Spacing, BorderRadius } from "@/shared/theme";

export const styles = StyleSheet.create({
  container: {
    paddingHorizontal: Spacing.base,
    paddingTop: Spacing.base,
    paddingBottom: Spacing.xxl,
  },
  determinationCard: {
    backgroundColor: "#EFF6FF",
    borderRadius: BorderRadius.md,
    padding: Spacing.base,
    borderWidth: 1.5,
    borderColor: "#3B82F6",
    marginBottom: Spacing.md,
  },
  determinationHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: Spacing.xs,
  },
  determinationTitleCol: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
  },
  determinationTitle: {
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.bold,
    color: "#1E40AF",
  },
  formBadge: {
    backgroundColor: "#1D4ED8",
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 6,
  },
  formBadgeText: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.bold,
    color: "#FFFFFF",
  },
  determinationRationale: {
    fontSize: Typography.fontSize.xs,
    color: "#1E3A8A",
    lineHeight: 18,
    marginTop: 4,
    marginBottom: Spacing.xs,
  },
  determinationCriteriaList: {
    gap: 4,
    marginTop: Spacing.xs,
    paddingTop: Spacing.xs,
    borderTopWidth: 1,
    borderTopColor: "#DBEAFE",
  },
  determinationCriteriaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  determinationCriteriaText: {
    fontSize: 11,
    color: "#1E40AF",
    fontWeight: Typography.fontWeight.medium,
  },
  sectionTitle: {
    fontSize: Typography.fontSize.base,
    fontWeight: Typography.fontWeight.bold,
    color: "#0F172A",
    marginBottom: 4,
  },
  sectionSubtitle: {
    fontSize: Typography.fontSize.xs,
    color: "#64748B",
    marginBottom: Spacing.md,
    lineHeight: 18,
  },
  sourceSelectorCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.md,
    padding: Spacing.base,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginBottom: Spacing.md,
  },
  sourceSelectorTitle: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.bold,
    color: "#334155",
    marginBottom: Spacing.xs,
  },
  sourceChipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  sourceChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#F8FAFC",
  },
  sourceChipActive: {
    borderColor: BrandColors.PRIMARY_ORANGE,
    backgroundColor: "#FEF0E6",
  },
  sourceChipText: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.medium,
    color: "#475569",
  },
  sourceChipTextActive: {
    color: BrandColors.PRIMARY_ORANGE_DARK,
    fontWeight: Typography.fontWeight.bold,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.md,
    padding: Spacing.base,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginBottom: Spacing.md,
  },
  cardActive: {
    borderColor: BrandColors.PRIMARY_ORANGE,
  },
  sourceHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sourceHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    flex: 1,
  },
  sourceIconBox: {
    width: 38,
    height: 38,
    borderRadius: BorderRadius.sm,
    backgroundColor: "#F1F5F9",
    justifyContent: "center",
    alignItems: "center",
  },
  sourceIconBoxActive: {
    backgroundColor: "#FEF0E6",
  },
  sourceTitleCol: {
    flex: 1,
  },
  sourceTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  sourceTitle: {
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.bold,
    color: "#0F172A",
  },
  sourceSubtitle: {
    fontSize: Typography.fontSize.xs - 1,
    color: "#64748B",
    marginTop: 1,
  },
  sourceTagVerified: {
    backgroundColor: "#DCFCE7",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  sourceTagVerifiedText: {
    fontSize: 10,
    fontWeight: Typography.fontWeight.bold,
    color: "#166534",
  },
  sourceTagImported: {
    backgroundColor: "#EAF1FE",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  sourceTagImportedText: {
    fontSize: 10,
    fontWeight: Typography.fontWeight.bold,
    color: "#083B75",
  },
  sourceTagWarning: {
    backgroundColor: "#FEF3C7",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  sourceTagWarningText: {
    fontSize: 10,
    fontWeight: Typography.fontWeight.bold,
    color: "#B45309",
  },
  checkboxBtn: {
    padding: 4,
  },
  expandedForm: {
    marginTop: Spacing.md,
    paddingTop: Spacing.md,
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
    gap: Spacing.sm,
  },
  form16Card: {
    backgroundColor: "#F8FAFC",
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: Spacing.sm,
    marginBottom: Spacing.xs,
    gap: 6,
  },
  form16TopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  form16Title: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.bold,
    color: "#083B75",
  },
  form16StatsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 4,
  },
  form16StatLabel: {
    fontSize: Typography.fontSize.xs,
    color: "#64748B",
  },
  form16StatValue: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.bold,
    color: "#0F172A",
  },
  brokerStatementCard: {
    backgroundColor: "#F8FAFC",
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: Spacing.sm,
    marginBottom: Spacing.xs,
    gap: 4,
  },
  brokerTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  brokerTitle: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.bold,
    color: "#083B75",
  },
  aisTable: {
    backgroundColor: "#F8FAFC",
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: Spacing.sm,
    gap: 6,
    marginBottom: Spacing.xs,
  },
  aisRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  aisLabel: {
    fontSize: Typography.fontSize.xs,
    color: "#475569",
  },
  aisValue: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.bold,
    color: "#0F172A",
  },
  aisNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 4,
  },
  aisNoticeText: {
    fontSize: 11,
    color: "#64748B",
  },
  schemeRadioGroup: {
    gap: Spacing.xs,
    marginBottom: Spacing.sm,
  },
  schemeRadioCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    backgroundColor: "#F8FAFC",
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    borderRadius: BorderRadius.sm,
    padding: Spacing.sm,
  },
  schemeRadioCardSelected: {
    borderColor: BrandColors.PRIMARY_ORANGE,
    backgroundColor: "#FEF0E6",
  },
  schemeRadioTextCol: {
    flex: 1,
  },
  schemeRadioTitle: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.bold,
    color: "#0F172A",
  },
  schemeRadioSub: {
    fontSize: 11,
    color: "#64748B",
    marginTop: 1,
  },
  inputRow: {
    flexDirection: "row",
    gap: Spacing.md,
  },
  inputGroupHalf: {
    flex: 1,
  },
  inputGroup: {
    marginBottom: Spacing.xs,
  },
  inputLabel: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.semiBold,
    color: "#334155",
    marginBottom: 4,
  },
  inputBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: BorderRadius.sm,
    paddingHorizontal: Spacing.sm,
    height: 44,
  },
  currencyPrefix: {
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.bold,
    color: "#083B75",
    marginRight: 4,
  },
  textInput: {
    flex: 1,
    fontSize: Typography.fontSize.sm,
    color: "#0F172A",
    height: "100%",
  },
  pillRow: {
    flexDirection: "row",
    gap: Spacing.xs,
    marginBottom: Spacing.xs,
  },
  pill: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  pillSelected: {
    borderColor: BrandColors.PRIMARY_ORANGE,
    backgroundColor: "#FEF0E6",
  },
  pillText: {
    fontSize: Typography.fontSize.xs - 1,
    fontWeight: Typography.fontWeight.semiBold,
    color: "#475569",
  },
  pillTextSelected: {
    color: BrandColors.PRIMARY_ORANGE_DARK,
    fontWeight: Typography.fontWeight.bold,
  },
  tagWrapRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: Spacing.xs,
  },
  filterTag: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#F8FAFC",
  },
  filterTagSelected: {
    borderColor: BrandColors.PRIMARY_ORANGE,
    backgroundColor: "#FEF0E6",
  },
  filterTagText: {
    fontSize: Typography.fontSize.xs - 1,
    color: "#64748B",
    fontWeight: Typography.fontWeight.medium,
  },
  filterTagTextSelected: {
    color: BrandColors.PRIMARY_ORANGE_DARK,
    fontWeight: Typography.fontWeight.bold,
  },
  fnoWarningBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#EFF6FF",
    borderRadius: BorderRadius.sm,
    padding: Spacing.sm,
    marginTop: 4,
  },
  fnoWarningText: {
    flex: 1,
    fontSize: 11,
    color: "#1E40AF",
    lineHeight: 16,
  },
  cryptoWarningBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#FEF2F2",
    borderRadius: BorderRadius.sm,
    padding: Spacing.sm,
    marginTop: 4,
  },
  cryptoWarningText: {
    flex: 1,
    fontSize: 11,
    color: "#991B1B",
    lineHeight: 16,
  },
  continueButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: BrandColors.PRIMARY_ORANGE,
    paddingVertical: Spacing.base,
    borderRadius: BorderRadius.md,
    gap: Spacing.xs,
    marginTop: Spacing.sm,
  },
  continueButtonText: {
    fontSize: Typography.fontSize.base,
    fontWeight: Typography.fontWeight.bold,
    color: "#FFFFFF",
  },
});
