/**
 * Component: GstApplicationStatusStep
 * Migrated from internal StyleSheet to external styles module.
 * Uses shared design tokens from src/shared/theme.ts.
 */

import { StyleSheet, Platform } from "react-native";
import { BrandColors } from "@/shared/theme";

export const styles = StyleSheet.create({
  container: {
    paddingTop: 4,
    paddingBottom: 20,
  },
  successBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ECFDF5",
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#A7F3D0",
    gap: 12,
  },
  successIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#10B981",
    justifyContent: "center",
    alignItems: "center",
  },
  successTextContainer: {
    flex: 1,
  },
  successTitle: {
    fontSize: 14.5,
    fontWeight: "700",
    color: "#065F46",
  },
  successSubtitle: {
    fontSize: 12,
    color: "#047857",
    marginTop: 2,
    lineHeight: 16,
  },
  heroCard: {
    backgroundColor: BrandColors.PRIMARY_BLUE,
    borderRadius: 20,
    padding: 18,
    marginBottom: 20,
    shadowColor: "#083B75",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 3,
  },
  heroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  heroAppIdLabel: {
    fontSize: 11,
    color: "rgba(255, 255, 255, 0.75)",
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  heroAppIdValue: {
    fontSize: 18,
    fontWeight: "800",
    color: BrandColors.WHITE,
    marginTop: 2,
    letterSpacing: 0.5,
    fontFamily: Platform.select({ ios: "System", android: "sans-serif-medium" }),
  },
  statusBadge: {
    backgroundColor: "#FEF3C7",
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 14,
  },
  statusBadgeText: {
    fontSize: 11.5,
    fontWeight: "700",
    color: "#92400E",
  },
  heroDetailsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.15)",
    paddingTop: 14,
  },
  heroCol: {
    flex: 1,
  },
  colLabel: {
    fontSize: 11,
    color: "rgba(255, 255, 255, 0.75)",
    marginBottom: 3,
  },
  colValue: {
    fontSize: 12.5,
    fontWeight: "700",
    color: BrandColors.WHITE,
    fontFamily: Platform.select({ ios: "System", android: "sans-serif-medium" }),
  },
  sectionHeading: {
    fontSize: 15,
    fontWeight: "700",
    color: BrandColors.TEXT_PRIMARY,
    marginBottom: 16,
    fontFamily: Platform.select({ ios: "System", android: "sans-serif-medium" }),
  },
  timelineList: {
    paddingLeft: 4,
    marginBottom: 20,
  },
  timelineRow: {
    flexDirection: "row",
    minHeight: 50,
  },
  timelineLeftCol: {
    alignItems: "center",
    width: 32,
    marginRight: 12,
  },
  circleCompleted: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#FEF0E6",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#FFD8BF",
  },
  circleActive: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: BrandColors.PRIMARY_ORANGE,
    justifyContent: "center",
    alignItems: "center",
  },
  innerDotActive: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: BrandColors.WHITE,
  },
  circlePending: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#F1F5F9",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  innerDotPending: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#CBD5E1",
  },
  timelineTrack: {
    flex: 1,
    width: 2,
    backgroundColor: "#E2E8F0",
    marginVertical: 4,
  },
  timelineTrackCompleted: {
    backgroundColor: "#FFD8BF",
  },
  timelineRightCol: {
    flex: 1,
    paddingBottom: 14,
  },
  stepTitle: {
    fontSize: 13.5,
    fontWeight: "700",
    color: BrandColors.TEXT_PRIMARY,
    marginBottom: 2,
    fontFamily: Platform.select({ ios: "System", android: "sans-serif-medium" }),
  },
  stepTitlePending: {
    color: "#94A3B8",
    fontWeight: "600",
  },
  stepSubtitle: {
    fontSize: 12,
    color: "#64748B",
    fontFamily: Platform.select({ ios: "System", android: "sans-serif" }),
  },
  actionButtonsCol: {
    gap: 10,
    marginTop: 4,
  },
  reuploadBtn: {
    height: 48,
    borderRadius: 24,
    backgroundColor: "#F0F9FF",
    borderWidth: 1.5,
    borderColor: "#BAE6FD",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  reuploadBtnText: {
    fontSize: 13.5,
    fontWeight: "700",
    color: "#0284C7",
    fontFamily: Platform.select({ ios: "System", android: "sans-serif-medium" }),
  },
  primaryHomeBtn: {
    height: 50,
    borderRadius: 25,
    backgroundColor: BrandColors.PRIMARY_ORANGE,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    shadowColor: BrandColors.PRIMARY_ORANGE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 3,
  },
  primaryHomeBtnText: {
    fontSize: 14.5,
    fontWeight: "700",
    color: BrandColors.WHITE,
    fontFamily: Platform.select({ ios: "System", android: "sans-serif-medium" }),
  },
  secondaryAppBtn: {
    height: 48,
    borderRadius: 24,
    backgroundColor: "#EAF1FE",
    borderWidth: 1,
    borderColor: "rgba(8, 59, 117, 0.15)",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  secondaryAppBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: BrandColors.PRIMARY_BLUE,
    fontFamily: Platform.select({ ios: "System", android: "sans-serif-medium" }),
  },
  contactSupportBtn: {
    height: 44,
    borderRadius: 22,
    backgroundColor: BrandColors.WHITE,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
  },
  contactSupportBtnText: {
    fontSize: 13.5,
    fontWeight: "600",
    color: "#64748B",
    fontFamily: Platform.select({ ios: "System", android: "sans-serif" }),
  },
});
