import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    padding: 16,
    backgroundColor: '#F8FAFC',
  },
  heading: {
    fontSize: 20,
    fontWeight: '700',
    color: '#083B75',
    marginBottom: 4,
  },
  subheading: {
    fontSize: 13,
    color: '#64748B',
    marginBottom: 16,
    lineHeight: 18,
  },
  metaCard: {
    backgroundColor: '#083B75',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  metaId: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  metaText: {
    fontSize: 13,
    color: '#E0F2FE',
    fontWeight: '600',
    marginTop: 2,
  },
  metaSub: {
    fontSize: 12,
    color: '#93C5FD',
    marginTop: 4,
  },
  timeline: {
    paddingLeft: 4,
    marginBottom: 16,
  },
  stageRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  iconColumn: {
    alignItems: 'center',
    marginRight: 12,
    width: 24,
  },
  line: {
    width: 2,
    minHeight: 44,
    backgroundColor: '#CBD5E1',
    marginTop: 4,
  },
  lineCompleted: {
    backgroundColor: '#166534',
  },
  stageContent: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  stageTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
  },
  stageDesc: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 3,
    lineHeight: 16,
  },
  statusFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  stageTime: {
    fontSize: 11,
    color: '#64748B',
    fontWeight: '500',
  },
  statusCurrentText: {
    fontSize: 11,
    color: '#EA580C',
    fontWeight: '700',
  },
  statusPendingText: {
    fontSize: 11,
    color: '#94A3B8',
    fontWeight: '500',
  },
  statusCompletedText: {
    fontSize: 11,
    color: '#166534',
    fontWeight: '700',
  },
  buttonsContainer: {
    marginTop: 8,
    marginBottom: 24,
    gap: 12,
  },
  homeBtn: {
    backgroundColor: '#F97316',
    borderRadius: 10,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  homeBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  trackBtn: {
    backgroundColor: '#F1F5F9',
    borderRadius: 10,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  trackBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#475569',
  },
});
