import { StyleSheet } from "react-native";
import { BorderRadius, Typography } from "@/shared/theme";

export const styles = StyleSheet.create({
  fieldGroup: {
    gap: 6,
    marginBottom: 14,
  },
  fieldLabel: {
    fontSize: Typography.fontSize.sm + 1,
    fontWeight: "700",
    color: "#0F172A",
  },
  star: {
    color: "#EF4444",
  },
  input: {
    height: 50,
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.base,
    borderWidth: 1.5,
    borderColor: "#CBD5E1",
    paddingHorizontal: 14,
    fontSize: Typography.fontSize.base,
    color: "#0F172A",
    fontWeight: "500",
  },
  inputError: {
    borderColor: "#EF4444",
    backgroundColor: "#FEF2F2",
  },
  fieldCounterRow: {
    alignItems: "flex-end",
    marginTop: 2,
  },
  fieldCounterText: {
    fontSize: Typography.fontSize.xs,
    color: "#94A3B8",
    fontWeight: "500",
  },
  errorText: {
    fontSize: Typography.fontSize.xs + 1,
    color: "#EF4444",
    fontWeight: "600",
    marginTop: 2,
  },
  dropdownSelect: {
    height: 50,
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.base,
    borderWidth: 1.5,
    borderColor: "#CBD5E1",
    paddingHorizontal: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dropdownSelectText: {
    fontSize: Typography.fontSize.base,
    color: "#0F172A",
    fontWeight: "500",
  },
  dropdownPlaceholderText: {
    fontSize: Typography.fontSize.base,
    color: "#94A3B8",
    fontWeight: "500",
  },
  dateInputWrap: {
    height: 50,
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.base,
    borderWidth: 1.5,
    borderColor: "#CBD5E1",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
  },
  dateTextInput: {
    flex: 1,
    fontSize: Typography.fontSize.base,
    color: "#0F172A",
    fontWeight: "500",
  },
  dateIconBox: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "#E0F2FE",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  phoneInputWrap: {
    height: 50,
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.base,
    borderWidth: 1.5,
    borderColor: "#CBD5E1",
    flexDirection: "row",
    alignItems: "center",
    overflow: "hidden",
  },
  phonePrefixBox: {
    backgroundColor: "#F1F5F9",
    height: "100%",
    paddingHorizontal: 12,
    justifyContent: "center",
    alignItems: "center",
    borderRightWidth: 1,
    borderRightColor: "#CBD5E1",
  },
  phonePrefixText: {
    fontSize: Typography.fontSize.base,
    color: "#475569",
    fontWeight: "600",
  },
  phoneTextInput: {
    flex: 1,
    paddingHorizontal: 12,
    fontSize: Typography.fontSize.base,
    color: "#0F172A",
    fontWeight: "500",
  },
});
