import { StyleSheet } from "react-native";
import { BrandColors } from "../../../../../shared/theme";

export const styles = StyleSheet.create({
  container: {
    paddingBottom: 24,
  },
  card: {
    backgroundColor: BrandColors.WHITE,
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#0F2052",
    marginBottom: 4,
  },
  sectionSubtitle: {
    fontSize: 13,
    color: "#64748B",
    marginBottom: 20,
    lineHeight: 18,
  },
  fieldGroup: {
    marginBottom: 18,
  },
  label: {
    fontSize: 13,
    fontWeight: "700",
    color: "#0F2052",
    marginBottom: 6,
  },
  requiredStar: {
    color: "#EF4444",
  },
  dropdownBox: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: BrandColors.WHITE,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  dropdownText: {
    fontSize: 14,
    color: "#0F2052",
    fontWeight: "500",
  },
  dropdownPlaceholder: {
    fontSize: 14,
    color: "#334155",
    fontWeight: "400",
  },
  dropdownMenu: {
    backgroundColor: BrandColors.WHITE,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: 8,
    marginTop: 4,
    overflow: "hidden",
  },
  dropdownMenuItem: {
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  dropdownMenuItemActive: {
    backgroundColor: "#F0F7FF",
  },
  dropdownMenuText: {
    fontSize: 13,
    color: "#334155",
    fontWeight: "500",
  },
  dropdownMenuTextActive: {
    color: "#0F4C81",
    fontWeight: "700",
  },
  amountRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: BrandColors.WHITE,
  },
  currencyPrefix: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#F1F5F9",
    borderRightWidth: 1,
    borderRightColor: "#CBD5E1",
    justifyContent: "center",
    alignItems: "center",
  },
  currencyPrefixText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#0F2052",
  },
  amountInput: {
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    fontWeight: "600",
    color: "#0F2052",
  },
  helperText: {
    fontSize: 11,
    color: "#64748B",
    marginTop: 6,
    lineHeight: 15,
  },
  errorText: {
    fontSize: 11,
    color: "#EF4444",
    marginTop: 4,
  },
  inputError: {
    borderColor: "#EF4444",
  },
  segmentedToggle: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#0F4C81",
    borderRadius: 8,
    overflow: "hidden",
    marginTop: 4,
  },
  toggleOption: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: BrandColors.WHITE,
  },
  toggleOptionActive: {
    backgroundColor: "#0F4C81",
  },
  toggleOptionText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#0F2052",
  },
  toggleOptionTextActive: {
    color: BrandColors.WHITE,
  },
  emiCard: {
    backgroundColor: "#F0F6FF",
    borderRadius: 12,
    padding: 14,
    marginTop: 10,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  calcIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#DBEAFE",
    alignItems: "center",
    justifyContent: "center",
  },
  emiContent: {
    flex: 1,
  },
  emiHeader: {
    fontSize: 11,
    fontWeight: "600",
    color: "#475569",
  },
  emiAmountRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 4,
    marginTop: 2,
    marginBottom: 4,
  },
  emiAmount: {
    fontSize: 22,
    fontWeight: "800",
    color: "#0F2052",
  },
  emiPeriod: {
    fontSize: 12,
    fontWeight: "600",
    color: "#475569",
  },
  emiSubtitle: {
    fontSize: 11,
    color: "#64748B",
    lineHeight: 15,
  },
});
