import { TdsDocumentItem } from "../types/tdsDocuments.types";

export const INITIAL_TDS_DOCUMENTS: TdsDocumentItem[] = [
  {
    id: "pan",
    title: "PAN",
    subtitle: "Permanent Account Number Card • up to 2 MB",
    isMandatory: true,
    acceptedFormats: "PDF, JPG, PNG • max 2 MB",
    allowedExtensions: ["pdf", "jpg", "jpeg", "png"],
    iconType: "pan",
    status: "not_uploaded",
  },
  {
    id: "form16",
    title: "Form 16 (Part A & B)",
    subtitle: "TDS Certificate issued by employer • up to 2 MB",
    isMandatory: true,
    acceptedFormats: "PDF, JPG, PNG • max 2 MB",
    allowedExtensions: ["pdf", "jpg", "jpeg", "png"],
    iconType: "form16",
    status: "not_uploaded",
  },
  {
    id: "form16a",
    title: "Form 16A",
    subtitle: "Non-salary TDS Certificate from banks/others • up to 2 MB",
    isMandatory: false,
    acceptedFormats: "PDF, JPG, PNG • max 2 MB",
    allowedExtensions: ["pdf", "jpg", "jpeg", "png"],
    iconType: "form16a",
    status: "not_uploaded",
  },
  {
    id: "ais",
    title: "AIS",
    subtitle: "Annual Information Statement from IT Portal • up to 2 MB",
    isMandatory: true,
    acceptedFormats: "PDF, Excel (XLSX, XLS) • max 2 MB",
    allowedExtensions: ["pdf", "xlsx", "xls", "json"],
    iconType: "ais",
    status: "not_uploaded",
  },
  {
    id: "tis",
    title: "TIS",
    subtitle: "Taxpayer Information Summary • up to 2 MB",
    isMandatory: false,
    acceptedFormats: "PDF, Excel (XLSX, XLS) • max 2 MB",
    allowedExtensions: ["pdf", "xlsx", "xls", "json"],
    iconType: "tis",
    status: "not_uploaded",
  },
  {
    id: "bank_statements",
    title: "Bank Statements",
    subtitle: "Last 6–12 months bank statements • up to 2 MB",
    isMandatory: true,
    acceptedFormats: "PDF, Excel, JPG, PNG • max 2 MB",
    allowedExtensions: ["pdf", "xlsx", "xls", "jpg", "jpeg", "png"],
    iconType: "bank_statements",
    status: "not_uploaded",
  },
  {
    id: "prev_itr",
    title: "Previous ITR",
    subtitle: "Previous assessment year filed acknowledgment • up to 2 MB",
    isMandatory: false,
    acceptedFormats: "PDF, JSON • max 2 MB",
    allowedExtensions: ["pdf", "json"],
    iconType: "prev_itr",
    status: "not_uploaded",
  },
  {
    id: "tds_certs",
    title: "TDS Certificates",
    subtitle: "Form 16B/16C or other deduction proofs • up to 2 MB",
    isMandatory: true,
    acceptedFormats: "PDF, JPG, PNG • max 2 MB",
    allowedExtensions: ["pdf", "jpg", "jpeg", "png"],
    iconType: "tds_certs",
    status: "not_uploaded",
  },
  {
    id: "income_proofs",
    title: "Supporting Income Documents",
    subtitle: "Interest certificates, capital gain sheets • up to 2 MB",
    isMandatory: false,
    acceptedFormats: "PDF, JPG, PNG, Excel, Word • max 2 MB",
    allowedExtensions: ["pdf", "jpg", "jpeg", "png", "xlsx", "xls", "doc", "docx"],
    iconType: "income_proofs",
    status: "not_uploaded",
  },
];
