import { StyleSheet } from "react-native";
import { BrandColors, Typography, Spacing, BorderRadius } from "../../../../../shared/theme";

export const styles = StyleSheet.create({
  container: {
    paddingBottom: Spacing.md,
  },
  topHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 10,
    gap: 8,
  },
  titleCol: {
    flex: 1,
  },
  sectionTitle: {
    fontSize: Typography.fontSize.base,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: 2,
  },
  sectionSubtitle: {
    fontSize: Typography.fontSize.xs,
    color: "#64748B",
    lineHeight: 16,
  },
  formatsNoticeBox: {
    backgroundColor: BrandColors.PRIMARY_LIGHT_ORANGE || "#FEF0E6",
    borderWidth: 1,
    borderColor: "#FFD8A8",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    maxWidth: 150,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  formatsNoticeText: {
    fontSize: 9,
    color: BrandColors.PRIMARY_ORANGE_DARK || "#EA580C",
    lineHeight: 12,
    fontWeight: "500",
  },
  docCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.sm,
    padding: 10,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.02,
    shadowRadius: 2,
    elevation: 1,
  },
  docCardLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    marginRight: 8,
    gap: 8,
  },
  iconSquare: {
    width: 30,
    height: 30,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  iconSquareBlue: {
    backgroundColor: "#E0F2FE",
  },
  iconSquarePurple: {
    backgroundColor: "#F3E8FF",
  },
  iconSquareGreen: {
    backgroundColor: "#DCFCE7",
  },
  iconSquareRed: {
    backgroundColor: "#FEE2E2",
  },
  iconSquareOrange: {
    backgroundColor: BrandColors.PRIMARY_LIGHT_ORANGE || "#FEF0E6",
  },
  iconSquarePink: {
    backgroundColor: "#FCE7F3",
  },
  docTextCol: {
    flex: 1,
  },
  docTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    flexWrap: "wrap",
  },
  docTitle: {
    fontSize: Typography.fontSize.xs,
    fontWeight: "700",
    color: "#0F172A",
  },
  requiredStar: {
    color: "#EF4444",
    fontSize: Typography.fontSize.xs,
    fontWeight: "700",
  },
  optionalBadge: {
    backgroundColor: "#E0F2FE",
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 4,
    marginLeft: 3,
  },
  optionalText: {
    fontSize: 9,
    fontWeight: "600",
    color: "#0284C7",
  },
  docSubtitle: {
    fontSize: 10,
    color: "#64748B",
    marginTop: 1,
    lineHeight: 13,
  },
  docCardRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  statusUploaded: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  statusUploadedText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#166534",
  },
  statusPending: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  statusPendingText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#64748B",
  },
  viewBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 6,
    backgroundColor: "#F1F5F9",
    borderWidth: 1,
    borderColor: "#CBD5E1",
  },
  viewBtnText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#0F172A",
  },
  deleteBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 6,
    backgroundColor: "#FEF2F2",
    borderWidth: 1,
    borderColor: "#FCA5A5",
  },
  deleteBtnText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#DC2626",
  },
  uploadBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: BrandColors.PRIMARY_LIGHT_ORANGE || "#FEF0E6",
    borderWidth: 1,
    borderColor: BrandColors.PRIMARY_ORANGE || "#FF7A00",
  },
  uploadBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: BrandColors.PRIMARY_ORANGE || "#FF7A00",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "flex-end",
  },
  sheetContent: {
    backgroundColor: BrandColors.WHITE,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 36,
  },
  sheetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sheetTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#0F172A",
  },
  sheetOption: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
    gap: 12,
  },
  sheetOptionText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#1E293B",
  },
  viewModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.65)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  viewModalContent: {
    width: "100%",
    backgroundColor: BrandColors.WHITE,
    borderRadius: 16,
    padding: 20,
    maxHeight: "85%",
  },
  previewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  previewTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  previewTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0F172A",
  },
  previewCard: {
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  previewImage: {
    width: "100%",
    height: 220,
    borderRadius: 8,
  },
  previewPdfBox: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 20,
    width: "100%",
  },
  previewBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#DCFCE7",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
    marginTop: 10,
    marginBottom: 8,
  },
  previewBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#166534",
  },
  previewFileName: {
    fontSize: 13,
    fontWeight: "600",
    color: "#334155",
    textAlign: "center",
  },
  previewMetaText: {
    fontSize: 11,
    color: "#64748B",
    marginTop: 4,
  },
  closePreviewBtn: {
    backgroundColor: "#0F172A",
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  closePreviewBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: BrandColors.WHITE,
  },
  sectionDivider: {
    marginTop: 14,
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionDividerTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#0F172A",
    letterSpacing: 0.2,
  },
  sectionDividerBadge: {
    backgroundColor: BrandColors.PRIMARY_LIGHT_ORANGE || "#FEF0E6",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  sectionDividerBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: BrandColors.PRIMARY_ORANGE_DARK || "#EA580C",
  },
});
