import { StyleSheet } from "react-native";
import { BrandColors } from "../../../../../shared/theme";

export const styles = StyleSheet.create({
  container: {
    paddingBottom: 24,
  },
  topHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 14,
    gap: 10,
  },
  titleCol: {
    flex: 1,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: 4,
  },
  sectionSubtitle: {
    fontSize: 12,
    color: "#64748B",
    lineHeight: 16,
  },
  formatsNoticeBox: {
    backgroundColor: "#FFF7ED",
    borderWidth: 1,
    borderColor: "#FFEDD5",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    maxWidth: 160,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  formatsNoticeText: {
    fontSize: 9,
    color: "#C2410C",
    lineHeight: 12,
    fontWeight: "500",
  },
  docCard: {
    backgroundColor: BrandColors.WHITE,
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  docCardLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    marginRight: 8,
    gap: 10,
  },
  iconSquare: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  docTextCol: {
    flex: 1,
  },
  docTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    flexWrap: "wrap",
  },
  docTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#0F172A",
  },
  requiredStar: {
    color: "#EF4444",
    fontSize: 13,
    fontWeight: "700",
  },
  optionalBadge: {
    backgroundColor: "#E0F2FE",
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 4,
    marginLeft: 4,
  },
  optionalText: {
    fontSize: 10,
    fontWeight: "600",
    color: "#0284C7",
  },
  docSubtitle: {
    fontSize: 11,
    color: "#64748B",
    marginTop: 2,
    lineHeight: 14,
  },
  docCardRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  statusUploaded: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  statusUploadedText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#166534",
  },
  statusPending: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  statusPendingText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#64748B",
  },
  viewBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 6,
    backgroundColor: "#F1F5F9",
    borderWidth: 1,
    borderColor: "#CBD5E1",
  },
  viewBtnText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#0F172A",
  },
  deleteBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 6,
    backgroundColor: "#FEF2F2",
    borderWidth: 1,
    borderColor: "#FCA5A5",
  },
  deleteBtnText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#DC2626",
  },
  uploadBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: "#FFF7ED",
    borderWidth: 1,
    borderColor: "#FFD8A8",
  },
  uploadBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#EA580C",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "flex-end",
  },
  sheetContent: {
    backgroundColor: BrandColors.WHITE,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 36,
  },
  sheetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sheetTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#0F172A",
  },
  sheetOption: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
    gap: 12,
  },
  sheetOptionText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#1E293B",
  },
  viewModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.65)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  viewModalContent: {
    width: "100%",
    backgroundColor: BrandColors.WHITE,
    borderRadius: 16,
    padding: 20,
    maxHeight: "85%",
  },
  previewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  previewTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  previewTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0F172A",
  },
  previewCard: {
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  previewImage: {
    width: "100%",
    height: 220,
    borderRadius: 8,
  },
  previewPdfBox: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 20,
    width: "100%",
  },
  previewBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#DCFCE7",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
    marginTop: 10,
    marginBottom: 8,
  },
  previewBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#166534",
  },
  previewFileName: {
    fontSize: 13,
    fontWeight: "600",
    color: "#334155",
    textAlign: "center",
  },
  previewMetaText: {
    fontSize: 11,
    color: "#64748B",
    marginTop: 4,
  },
  closePreviewBtn: {
    backgroundColor: "#0F172A",
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  closePreviewBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: BrandColors.WHITE,
  },
});
