import { StyleSheet } from "react-native";
import { BrandColors, Typography, Spacing, BorderRadius } from "@/shared/theme";

export const styles = StyleSheet.create({
  container: {
    paddingHorizontal: Spacing.base,
    paddingTop: Spacing.base,
    paddingBottom: Spacing.xxl,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.md,
    padding: Spacing.base,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginBottom: Spacing.md,
  },
  cardHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: Spacing.xs,
  },
  cardHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
  },
  cardTitle: {
    fontSize: Typography.fontSize.base,
    fontWeight: Typography.fontWeight.bold,
    color: "#0F172A",
  },
  cardDescription: {
    fontSize: Typography.fontSize.xs,
    color: "#64748B",
    marginBottom: Spacing.md,
    lineHeight: 18,
  },
  cardDescriptionAccordion: {
    fontSize: Typography.fontSize.xs,
    color: "#64748B",
    marginTop: Spacing.sm,
    marginBottom: Spacing.md,
    lineHeight: 18,
  },
  verifiedTag: {
    backgroundColor: "#DCFCE7",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  verifiedTagText: {
    fontSize: Typography.fontSize.xs - 1,
    fontWeight: Typography.fontWeight.bold,
    color: "#166534",
  },
  importedTag: {
    backgroundColor: "#EAF1FE",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  importedTagText: {
    fontSize: Typography.fontSize.xs - 1,
    fontWeight: Typography.fontWeight.bold,
    color: "#083B75",
  },
  readOnlyGrid: {
    gap: Spacing.sm,
    backgroundColor: "#F8FAFC",
    padding: Spacing.md,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  readOnlyRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  fieldLabel: {
    fontSize: Typography.fontSize.xs,
    color: "#64748B",
  },
  fieldValue: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.semiBold,
    color: "#0F172A",
  },
  fieldValueHighlight: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.bold,
    color: "#083B75",
  },
  editProfileBtn: {
    alignSelf: "flex-end",
    marginTop: Spacing.xs,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  editProfileText: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.semiBold,
    color: "#083B75",
    textDecorationLine: "underline",
  },
  pickerRow: {
    flexDirection: "row",
    gap: Spacing.xs,
    marginTop: 4,
  },
  pickerPill: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  pickerPillSelected: {
    borderColor: BrandColors.PRIMARY_ORANGE,
    backgroundColor: "#FEF0E6",
  },
  pickerPillText: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.semiBold,
    color: "#475569",
    textAlign: "center",
  },
  pickerPillTextSelected: {
    color: BrandColors.PRIMARY_ORANGE_DARK,
    fontWeight: Typography.fontWeight.bold,
  },
  suggestionBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: BorderRadius.sm,
    padding: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  suggestionTextCol: {
    flex: 1,
  },
  suggestionTitle: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.bold,
    color: "#083B75",
  },
  suggestionSub: {
    fontSize: 11,
    color: "#64748B",
    marginTop: 2,
    lineHeight: 16,
  },
  radioList: {
    gap: Spacing.sm,
  },
  radioCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#F8FAFC",
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    borderRadius: BorderRadius.sm,
    padding: Spacing.md,
    gap: Spacing.sm,
  },
  radioCardSelected: {
    borderColor: BrandColors.PRIMARY_ORANGE,
    backgroundColor: "#FEF0E6",
  },
  radioCardTextCol: {
    flex: 1,
  },
  radioCardTitle: {
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.bold,
    color: "#0F172A",
  },
  radioCardSubtitle: {
    fontSize: Typography.fontSize.xs,
    color: "#64748B",
    marginTop: 2,
    lineHeight: 16,
  },
  residencyConfirmCard: {
    backgroundColor: "#F8FAFC",
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: Spacing.md,
    marginBottom: Spacing.sm,
  },
  residencyConfirmCardTopSpaced: {
    backgroundColor: "#F8FAFC",
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: Spacing.md,
    marginBottom: Spacing.sm,
    marginTop: Spacing.md,
  },
  residencyPromptRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: Spacing.xs,
  },
  residencyPromptText: {
    fontSize: Typography.fontSize.sm,
    color: "#0F172A",
    lineHeight: 20,
  },
  residencyPromptHighlight: {
    fontWeight: Typography.fontWeight.bold,
    color: "#083B75",
  },
  confirmCheckRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: Spacing.xs,
  },
  confirmCheckText: {
    fontSize: Typography.fontSize.xs,
    color: "#334155",
    fontWeight: Typography.fontWeight.medium,
  },
  residencyDetailToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: Spacing.xs,
  },
  residencyDetailToggleText: {
    fontSize: Typography.fontSize.xs,
    color: "#083B75",
    fontWeight: Typography.fontWeight.semiBold,
  },
  residencyCriteriaBox: {
    backgroundColor: "#FFFFFF",
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: Spacing.sm,
    marginTop: Spacing.xs,
    gap: 4,
  },
  criteriaLine: {
    fontSize: 11,
    color: "#64748B",
    lineHeight: 16,
  },
  selectedBankCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F8FAFC",
    borderWidth: 1.5,
    borderColor: "#059669",
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
  },
  bankList: {
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  bankSelectableCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F8FAFC",
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
  },
  bankSelectableCardSelected: {
    borderColor: "#059669",
    backgroundColor: "#F0FDF4",
  },
  bankRadioCol: {
    marginLeft: Spacing.sm,
    alignItems: "center",
    justifyContent: "center",
  },
  bankInfoCol: {
    flex: 1,
    gap: 2,
  },
  bankTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
  },
  bankNameText: {
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.bold,
    color: "#0F172A",
  },
  bankMaskedNumber: {
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.bold,
    color: "#083B75",
    letterSpacing: 1,
  },
  bankSubText: {
    fontSize: 11,
    color: "#64748B",
  },
  changeBankBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#FFFFFF",
  },
  changeBankBtnText: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.semiBold,
    color: "#083B75",
  },
  accordionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  accordionHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
  },
  optionalTag: {
    backgroundColor: "#F1F5F9",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#CBD5E1",
  },
  optionalTagText: {
    fontSize: Typography.fontSize.xs - 1,
    fontWeight: Typography.fontWeight.semiBold,
    color: "#475569",
  },
  priorItrBox: {
    backgroundColor: "#F8FAFC",
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: Spacing.md,
    marginBottom: Spacing.sm,
    marginTop: Spacing.xs,
  },
  priorItrTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: Spacing.xs,
  },
  priorItrTitle: {
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.bold,
    color: "#0F172A",
  },
  importSectionTitle: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.bold,
    color: "#334155",
    marginTop: Spacing.xs,
    marginBottom: Spacing.xs,
  },
  importCheckRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 3,
  },
  importCheckText: {
    fontSize: Typography.fontSize.xs,
    color: "#475569",
  },
  inputLabel: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.semiBold,
    color: "#334155",
    marginBottom: 6,
  },
  continueButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: BrandColors.PRIMARY_ORANGE,
    paddingVertical: Spacing.base,
    borderRadius: BorderRadius.md,
    gap: Spacing.xs,
    marginTop: Spacing.sm,
  },
  continueButtonText: {
    fontSize: Typography.fontSize.base,
    fontWeight: Typography.fontWeight.bold,
    color: "#FFFFFF",
  },
});
