import { LoanDocumentItem } from "../../types/loans.types";

export const VEHICLE_LOAN_DOCUMENTS_TEMPLATE: LoanDocumentItem[] = [
  // 1. Identity & Address
  {
    id: "pan",
    name: "PAN Card",
    subtitle: "Clear photo or PDF copy of applicant PAN",
    required: true,
    iconName: "card",
    iconBg: "#FEF0E6",
    iconColor: "#EA580C",
    category: "Identity & Address",
  },
  {
    id: "aadhaar",
    name: "Aadhaar Card",
    subtitle: "Front & back copy with readable QR code",
    required: true,
    iconName: "finger-print",
    iconBg: "#FEF0E6",
    iconColor: "#EA580C",
    category: "Identity & Address",
  },
  {
    id: "driving-license",
    name: "Driving License",
    subtitle: "Valid driver license (mandatory auto loan KYC)",
    required: true,
    iconName: "car-outline",
    iconBg: "#FEF0E6",
    iconColor: "#EA580C",
    category: "Identity & Address",
  },
  {
    id: "photograph",
    name: "Passport Size Photograph",
    subtitle: "Recent passport photo of applicant",
    required: true,
    iconName: "camera",
    iconBg: "#FEF0E6",
    iconColor: "#EA580C",
    category: "Identity & Address",
  },
  {
    id: "address-proof",
    name: "Address Proof",
    subtitle: "Utility bill / Rent Agreement / Voter ID",
    required: true,
    iconName: "home",
    iconBg: "#FEF0E6",
    iconColor: "#EA580C",
    category: "Identity & Address",
  },

  // 2. Income & Banking
  {
    id: "bank-statements",
    name: "Bank Statements (6-12 Months)",
    subtitle: "Continuous bank statement of salary / primary account in PDF",
    required: true,
    iconName: "document-text",
    iconBg: "#FEF0E6",
    iconColor: "#EA580C",
    category: "Income & Banking",
  },
  {
    id: "salary-slips",
    name: "Salary Slips / Income Proof",
    subtitle: "Last 3-6 months payslips or business income statement",
    required: true,
    iconName: "receipt",
    iconBg: "#FEF0E6",
    iconColor: "#EA580C",
    category: "Income & Banking",
  },
  {
    id: "form-16-itr",
    name: "Form 16 / ITR & Computation (2 Years)",
    subtitle: "Latest 2 assessment years tax returns or Form 16 Part A & B",
    required: false,
    iconName: "stats-chart",
    iconBg: "#FEF0E6",
    iconColor: "#EA580C",
    category: "Income & Banking",
  },

  // 3. Vehicle Quotation & Collateral
  {
    id: "proforma-invoice",
    name: "Dealer Proforma Invoice / Quotation",
    subtitle: "Official quotation with on-road price breakup from dealer",
    required: true,
    iconName: "document-attach",
    iconBg: "#FEF0E6",
    iconColor: "#EA580C",
    category: "Collateral & Others",
  },
  {
    id: "rc-copy",
    name: "Vehicle RC Copy (For Used Vehicle)",
    subtitle: "Registration Certificate (front & back) if pre-owned vehicle",
    required: false,
    iconName: "shield-checkmark",
    iconBg: "#FEF0E6",
    iconColor: "#EA580C",
    category: "Collateral & Others",
  },
  {
    id: "down-payment-receipt",
    name: "Down Payment / Margin Money Receipt",
    subtitle: "Booking receipt or token advance paid to dealer",
    required: false,
    iconName: "cash",
    iconBg: "#FEF0E6",
    iconColor: "#EA580C",
    category: "Collateral & Others",
  },
];
