import type {
  SupportContactMethod,
  SupportConversation,
  SupportExecutive,
} from '../types/support.types'

export const SUPPORT_EXECUTIVES: SupportExecutive[] = [
  {
    id: 'exec_rohit',
    name: 'Rohit Kulkarni',
    role: 'GST Executive',
    department: 'GST Services',
    avatarInitials: 'RK',
    avatarColor: '#059669',
    status: 'Online',
    phone: '+91 20 4141 8800',
    email: 'rohit.k@taxedge.in',
    assignedAppId: 'GST-2026-00118',
  },
  {
    id: 'exec_meera',
    name: 'Meera Iyer',
    role: 'Tax Executive',
    department: 'Direct Tax & ITR',
    avatarInitials: 'MI',
    avatarColor: '#083B75',
    status: 'Online',
    phone: '+91 20 4141 8801',
    email: 'meera.i@taxedge.in',
    assignedAppId: 'ITR-2026-00342',
  },
  {
    id: 'exec_sameer',
    name: 'Sameer Joshi',
    role: 'Loan Executive',
    department: 'Business Loans',
    avatarInitials: 'SJ',
    avatarColor: '#D97706',
    status: 'Away',
    phone: '+91 20 4141 8802',
    email: 'sameer.j@taxedge.in',
    assignedAppId: 'LN-2026-00891',
  },
  {
    id: 'exec_sneha',
    name: 'Sneha Patil',
    role: 'Insurance Executive',
    department: 'General & Health Insurance',
    avatarInitials: 'SP',
    avatarColor: '#7C3AED',
    status: 'Online',
    phone: '+91 20 4141 8803',
    email: 'sneha.p@taxedge.in',
    assignedAppId: 'INS-2026-00412',
  },
]

export const INITIAL_SUPPORT_CONVERSATIONS: Record<string, SupportConversation> = {
  'GST-2026-00118': {
    id: 'conv_gst_00118',
    applicationId: '1',
    applicationRef: 'GST-2026-00118',
    serviceName: 'GST Monthly Filing',
    dateLabel: 'Application GST-2026-00118 · 28 August 2026',
    executive: SUPPORT_EXECUTIVES[0],
    messages: [
      {
        id: 'msg_1',
        conversationId: 'conv_gst_00118',
        senderId: 'user_current',
        senderType: 'user',
        senderName: 'You',
        text: 'Documents uploaded.',
        timestamp: '2026-08-28T10:04:00.000Z',
        formattedTime: '10:04 AM',
        status: 'read',
      },
      {
        id: 'msg_2',
        conversationId: 'conv_gst_00118',
        senderId: 'exec_rohit',
        senderType: 'executive',
        senderName: 'Rohit Kulkarni',
        text: 'Thank you. We are verifying your documents.',
        timestamp: '2026-08-28T10:11:00.000Z',
        formattedTime: '10:11 AM',
        status: 'read',
      },
      {
        id: 'msg_3',
        conversationId: 'conv_gst_00118',
        senderId: 'user_current',
        senderType: 'user',
        senderName: 'You',
        text: 'How long will processing take?',
        timestamp: '2026-08-28T10:12:00.000Z',
        formattedTime: '10:12 AM',
        status: 'read',
      },
      {
        id: 'msg_4',
        conversationId: 'conv_gst_00118',
        senderId: 'exec_rohit',
        senderType: 'executive',
        senderName: 'Rohit Kulkarni',
        text: 'Your application is currently under verification. GSTR-1 and 3B are usually filed within 2 working days of verification.',
        timestamp: '2026-08-28T10:15:00.000Z',
        formattedTime: '10:15 AM',
        status: 'read',
      },
      {
        id: 'msg_5',
        conversationId: 'conv_gst_00118',
        senderId: 'exec_rohit',
        senderType: 'executive',
        senderName: 'Rohit Kulkarni',
        text: 'One thing — invoice INV-2026-0442 is missing the buyer GSTIN. Could you please provide the updated invoice or the recipient GSTIN?',
        timestamp: '2026-08-28T10:16:00.000Z',
        formattedTime: '10:16 AM',
        status: 'read',
      },
    ],
  },
  'ITR-2026-00342': {
    id: 'conv_itr_00342',
    applicationId: '2',
    applicationRef: 'ITR-2026-00342',
    serviceName: 'ITR-2 Filing with Capital Gains',
    dateLabel: 'Application ITR-2026-00342 · 29 August 2026',
    executive: SUPPORT_EXECUTIVES[1],
    messages: [
      {
        id: 'msg_itr_1',
        conversationId: 'conv_itr_00342',
        senderId: 'exec_meera',
        senderType: 'executive',
        senderName: 'Meera Iyer',
        text: 'Hello! I have reviewed your Form 16 and capital gains statement. We are preparing the tax computation sheet.',
        timestamp: '2026-08-29T11:30:00.000Z',
        formattedTime: '11:30 AM',
        status: 'read',
      },
    ],
  },
  'LN-2026-00891': {
    id: 'conv_ln_00891',
    applicationId: '3',
    applicationRef: 'LN-2026-00891',
    serviceName: 'MSME Working Capital Loan',
    dateLabel: 'Application LN-2026-00891 · 30 August 2026',
    executive: SUPPORT_EXECUTIVES[2],
    messages: [
      {
        id: 'msg_ln_1',
        conversationId: 'conv_ln_00891',
        senderId: 'exec_sameer',
        senderType: 'executive',
        senderName: 'Sameer Joshi',
        text: 'Hi, your bank statements for the last 6 months have been submitted to our lending partner. I will update you once sanctioned.',
        timestamp: '2026-08-30T14:20:00.000Z',
        formattedTime: '02:20 PM',
        status: 'read',
      },
    ],
  },
}

export const SUPPORT_CONTACT_METHODS: SupportContactMethod[] = [
  {
    id: 'contact_phone',
    type: 'phone',
    label: 'Phone',
    value: '+91 20 4141 8800',
    actionUrl: 'tel:+912041418800',
    icon: 'phone',
  },
  {
    id: 'contact_whatsapp',
    type: 'whatsapp',
    label: 'WhatsApp',
    value: 'WhatsApp +91 98220 41880',
    actionUrl: 'https://wa.me/919822041880',
    icon: 'whatsapp',
  },
  {
    id: 'contact_email',
    type: 'email',
    label: 'Email',
    value: 'help@taxedge.in',
    actionUrl: 'mailto:help@taxedge.in',
    icon: 'email',
  },
  {
    id: 'contact_hours',
    type: 'hours',
    label: 'Working Hours',
    value: 'Mon–Sat, 10:00 to 19:00 IST',
    icon: 'clock',
  },
]

export const SECURITY_NOTICE_CONTENT = {
  title: 'We will never ask for an OTP',
  body: 'No one from TaxEdge will ask for your OTP, password or card PIN — on chat, on a call or on WhatsApp.',
}
