package com.taxedge.itr.taxnotice.enums;

public enum TaxNoticeDocumentType {

	TAX_NOTICE, PREVIOUS_ITR, ITR_ACKNOWLEDGEMENT, FORM_16_16A, AIS_AY, TIS, BANK_STATEMENT,
	SUPPORTING_INCOME_DOCUMENTS, SUPPORTING_EXPENSE_DOCUMENTS, PREVIOUS_TAX_RESPONSES, OTHER_NOTICE_SPECIFIC_DOCUMENTS
}