spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/taxedge_db}
    username: ${DB_USERNAME:mysql}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 150MB
