import { StyleSheet } from "react-native";

export const st = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#FAFCFF" },
  flex1: { flex: 1 },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingBottom: 10,
    backgroundColor: "#FFFFFF",
  },
  backBtn: { width: 36, height: 36, justifyContent: "center", alignItems: "center" },
  headerTitle: { fontSize: 17, fontWeight: "700", color: "#0F172A" },
  taxEdgeBadge: {
    flexDirection: "row",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: "#EFF6FF",
    borderWidth: 1,
    borderColor: "#DBEAFE",
  },
  taxText: { fontSize: 13, fontWeight: "800", color: "#1E5EFF" },
  edgeText: { fontSize: 13, fontWeight: "800", color: "#FF7A00" },
  inputScroll: { padding: 16, paddingBottom: 40, gap: 14 },
  heroContainer: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 4 },
  heroLeft: { flex: 1, paddingRight: 8 },
  heroKicker: { fontSize: 10, fontWeight: "800", color: "#FF7A00", letterSpacing: 0.8, marginBottom: 4 },
  heroTitle: { fontSize: 20, fontWeight: "800", color: "#0F172A", lineHeight: 26, marginBottom: 6 },
  heroSub: { fontSize: 11.5, color: "#64748B", lineHeight: 16 },
  heroGraphicWrap: { width: 84, height: 94, justifyContent: "center", alignItems: "center" },
  heroGlowCircle: { position: "absolute", width: 84, height: 84, borderRadius: 42, backgroundColor: "#DBEAFE", opacity: 0.6 },
  heroDoc: {
    width: 62,
    height: 76,
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#BFDBFE",
    padding: 6,
    shadowColor: "#1E5EFF",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  heroDocHeader: { height: 6, backgroundColor: "#1E5EFF", borderRadius: 3, marginBottom: 4 },
  heroDocGst: { fontSize: 10, fontWeight: "900", color: "#1E5EFF", textAlign: "center", marginBottom: 3 },
  heroDocLine: { height: 2.5, backgroundColor: "#E2E8F0", borderRadius: 2, marginBottom: 3 },
  heroDocLineShort: { height: 2.5, width: "65%", backgroundColor: "#E2E8F0", borderRadius: 2 },
  heroDownloadCircle: {
    position: "absolute",
    bottom: -6,
    right: -6,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "#1E5EFF",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#FFFFFF",
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "#EBF2FE",
    shadowColor: "#1E5EFF",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 1,
  },
  cardHeaderRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 10 },
  cardIconBox: { width: 32, height: 32, borderRadius: 8, backgroundColor: "#EFF6FF", justifyContent: "center", alignItems: "center" },
  cardLabel: { fontSize: 13.5, fontWeight: "700", color: "#0F172A" },
  star: { color: "#FF7A00" },
  input: {
    height: 46,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    paddingHorizontal: 12,
    fontSize: 14,
    color: "#0F172A",
    fontWeight: "600",
  },
  inputFocused: { borderColor: "#1E5EFF", backgroundColor: "#F8FAFF" },
  inputError: { borderColor: "#FF7A00", backgroundColor: "#FFF7ED" },
  errorText: { fontSize: 11.5, color: "#FF7A00", fontWeight: "600", marginTop: 4 },
  helperText: { fontSize: 11.5, color: "#94A3B8", marginTop: 4 },
  contactHeaderRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  editBtn: { flexDirection: "row", alignItems: "center", gap: 3 },
  editText: { fontSize: 12.5, fontWeight: "700", color: "#1E5EFF" },
  contactPhone: { fontSize: 14.5, fontWeight: "700", color: "#0F172A", marginLeft: 42 },
  contactEmail: { fontSize: 13, fontWeight: "500", color: "#64748B", marginLeft: 42, marginTop: 2 },
  contactSubText: { fontSize: 11, color: "#94A3B8", marginLeft: 42, marginTop: 6, lineHeight: 15 },
  dropdownBox: {
    height: 46,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    paddingHorizontal: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dropdownText: { fontSize: 13.5, fontWeight: "600", color: "#0F172A", flex: 1 },
  placeholderText: { color: "#94A3B8", fontWeight: "400" },
  infoCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EFF6FF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#DBEAFE",
    padding: 12,
  },
  infoText: { flex: 1, fontSize: 12, color: "#1E3A8A", lineHeight: 17, fontWeight: "500" },
  orangeCta: {
    height: 52,
    borderRadius: 26,
    backgroundColor: "#FF7A00",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 18,
    shadowColor: "#FF7A00",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 4,
  },
  orangeCtaDisabled: { opacity: 0.7 },
  orangeCtaText: { fontSize: 15, fontWeight: "800", color: "#FFFFFF", letterSpacing: 0.3 },
  ctaArrowCircle: { width: 26, height: 26, borderRadius: 13, backgroundColor: "#FFFFFF", justifyContent: "center", alignItems: "center" },
  footerRowCenter: { flexDirection: "row", justifyContent: "center", alignItems: "center", marginTop: 4 },
  verifiedText: { fontSize: 11.5, color: "#64748B", fontWeight: "600" },
  readyScroll: { padding: 18, alignItems: "center", paddingBottom: 40 },
  readyHeroWrap: { width: 180, height: 160, justifyContent: "center", alignItems: "center", marginVertical: 10 },
  podiumBase: { position: "absolute", bottom: 10, width: 150, height: 32, borderRadius: 16, backgroundColor: "#DBEAFE", opacity: 0.8 },
  podiumRing: { position: "absolute", bottom: 20, width: 120, height: 20, borderRadius: 10, borderWidth: 2, borderColor: "#1E5EFF", opacity: 0.6 },
  readyDocCard: {
    width: 88,
    height: 110,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#BFDBFE",
    padding: 8,
    alignItems: "center",
    shadowColor: "#1E5EFF",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 5,
  },
  docGstTag: { fontSize: 15, fontWeight: "900", color: "#1E5EFF", marginTop: 4, marginBottom: 8 },
  docLineWide: { width: "80%", height: 3, backgroundColor: "#DBEAFE", borderRadius: 2, marginBottom: 4 },
  docLineMed: { width: "60%", height: 3, backgroundColor: "#DBEAFE", borderRadius: 2, marginBottom: 4 },
  readyCheckBadge: {
    position: "absolute",
    bottom: 6,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#1E5EFF",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: "#FFFFFF",
  },
  confettiDot: { position: "absolute", width: 7, height: 7, borderRadius: 3.5 },
  readyTitle: { fontSize: 24, fontWeight: "900", color: "#0F172A", textAlign: "center", marginTop: 6 },
  readySub: { fontSize: 13, color: "#64748B", textAlign: "center", marginTop: 6, lineHeight: 18, paddingHorizontal: 12 },
  blueBold: { color: "#1E5EFF", fontWeight: "800" },
  detailsCard: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#EBF2FE",
    padding: 14,
    marginTop: 18,
    shadowColor: "#1E5EFF",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  detailRow: { flexDirection: "row", alignItems: "center", paddingVertical: 8 },
  detailIconBox: { width: 32, height: 32, borderRadius: 8, backgroundColor: "#EFF6FF", justifyContent: "center", alignItems: "center", marginRight: 10 },
  detailLabel: { fontSize: 12.5, color: "#64748B", fontWeight: "500", width: 90 },
  detailVal: { flex: 1, fontSize: 13, fontWeight: "700", color: "#0F172A", textAlign: "right" },
  statusPill: { flex: 1, alignItems: "flex-end" },
  statusPillText: { paddingHorizontal: 10, paddingVertical: 3, borderRadius: 12, backgroundColor: "#EFF6FF", color: "#1E5EFF", fontSize: 11.5, fontWeight: "700" },
  divider: { height: 1, backgroundColor: "#F1F5F9" },
  blueOutlineBtn: {
    height: 50,
    borderRadius: 25,
    backgroundColor: "#FFFFFF",
    borderWidth: 1.5,
    borderColor: "#1E5EFF",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  blueOutlineBtnText: { fontSize: 15, fontWeight: "800", color: "#1E5EFF" },
  textOnlyBtn: { height: 44, flexDirection: "row", justifyContent: "center", alignItems: "center", width: "100%" },
  textOnlyBtnText: { fontSize: 14, fontWeight: "600", color: "#64748B" },
  footerWrap: { marginTop: 24, alignItems: "center" },
  footerRow: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 4 },
  footerSafeText: { fontSize: 12, color: "#1E5EFF", fontWeight: "600" },
  footerGovText: { fontSize: 11, color: "#94A3B8" },
});
export default st;
