import { StyleSheet } from "react-native";
import { BrandColors, Typography, Spacing, BorderRadius } from "../../../../../shared/theme";

export const styles = StyleSheet.create({
  container: {
    paddingBottom: Spacing.md,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.md,
    padding: 14,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginBottom: 10,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 2,
    elevation: 1,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  iconBox: {
    width: 26,
    height: 26,
    borderRadius: 6,
    backgroundColor: "#FEF0E6",
    alignItems: "center",
    justifyContent: "center",
  },
  cardTitle: {
    fontSize: Typography.fontSize.xs + 1,
    fontWeight: "700",
    color: "#0F172A",
  },
  requiredStar: {
    color: "#EF4444",
  },
  infoIcon: {
    marginLeft: 4,
  },
  input: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: BorderRadius.sm,
    paddingHorizontal: 12,
    paddingVertical: 9,
    fontSize: Typography.fontSize.sm,
    color: "#0F172A",
  },
  inputError: {
    borderColor: "#EF4444",
  },
  // Dropdown Input Selector
  dropdownSelector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: BorderRadius.sm,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  dropdownSelectorActive: {
    borderColor: BrandColors.PRIMARY_ORANGE,
    backgroundColor: "#FFFBF7",
  },
  dropdownText: {
    fontSize: Typography.fontSize.sm,
    color: "#0F172A",
    fontWeight: Typography.fontWeight.medium,
  },
  dropdownPlaceholder: {
    fontSize: Typography.fontSize.sm,
    color: "#94A3B8",
  },
  customInputContainer: {
    marginTop: 8,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 8,
  },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 16,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  chipActive: {
    backgroundColor: "#FEF0E6",
    borderColor: BrandColors.PRIMARY_ORANGE,
  },
  chipText: {
    fontSize: 11,
    fontWeight: "500",
    color: "#475569",
  },
  chipTextActive: {
    color: BrandColors.PRIMARY_ORANGE_DARK || "#EA580C",
    fontWeight: "700",
  },
  profileRow: {
    flexDirection: "row",
    gap: 6,
  },
  profileBtn: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 6,
    borderRadius: BorderRadius.sm,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    alignItems: "center",
    justifyContent: "center",
  },
  profileBtnActive: {
    backgroundColor: "#FEF0E6",
    borderColor: BrandColors.PRIMARY_ORANGE,
  },
  profileBtnText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#475569",
    textAlign: "center",
  },
  profileBtnTextActive: {
    color: BrandColors.PRIMARY_ORANGE_DARK || "#EA580C",
    fontWeight: "700",
  },
  tenureGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  tenureBox: {
    width: "31.8%",
    paddingVertical: 8,
    paddingHorizontal: 4,
    borderRadius: BorderRadius.sm,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    alignItems: "center",
    justifyContent: "center",
  },
  tenureBoxActive: {
    backgroundColor: "#FEF0E6",
    borderColor: BrandColors.PRIMARY_ORANGE,
  },
  tenureText: {
    fontSize: 11,
    color: "#475569",
    fontWeight: "500",
    textAlign: "center",
  },
  tenureTextActive: {
    color: BrandColors.PRIMARY_ORANGE_DARK || "#EA580C",
    fontWeight: "700",
  },
  tenureBoxCustom: {
    backgroundColor: "#FFFFFF",
    borderColor: BrandColors.PRIMARY_ORANGE || "#FF7A00",
  },
  tenureBoxCustomActive: {
    backgroundColor: "#FEF0E6",
    borderColor: BrandColors.PRIMARY_ORANGE || "#FF7A00",
  },
  tenureTextCustom: {
    color: BrandColors.PRIMARY_ORANGE || "#FF7A00",
    fontWeight: "600",
  },
  tenureTextCustomActive: {
    color: BrandColors.PRIMARY_ORANGE_DARK || "#EA580C",
    fontWeight: "700",
  },
  customTenureSection: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
  },
  customTenureTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: "#0F172A",
    marginBottom: 8,
  },
  customTenureInput: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1.5,
    borderColor: BrandColors.PRIMARY_ORANGE || "#FF7A00",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: "#0F172A",
  },
  tenureEquivalentText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#475569",
    marginTop: 6,
  },
  radioGroup: {
    flexDirection: "row",
    gap: 8,
  },
  radioCard: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: BorderRadius.sm,
    padding: 10,
    gap: 8,
  },
  radioCardActive: {
    backgroundColor: "#FFFBF7",
    borderColor: BrandColors.PRIMARY_ORANGE,
  },
  radioOuter: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#CBD5E1",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  radioOuterActive: {
    borderColor: BrandColors.PRIMARY_ORANGE,
  },
  radioInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: BrandColors.PRIMARY_ORANGE,
  },
  radioContent: {
    flex: 1,
  },
  radioTitle: {
    fontSize: Typography.fontSize.xs,
    fontWeight: "700",
    color: "#0F172A",
    marginBottom: 2,
  },
  radioSubtitle: {
    fontSize: 10,
    color: "#64748B",
    lineHeight: 13,
  },
  subCard: {
    backgroundColor: BrandColors.PRIMARY_LIGHT_ORANGE || "#FEF0E6",
    borderWidth: 1,
    borderColor: "#FFD8A8",
    borderRadius: 10,
    padding: 14,
    marginTop: 12,
  },
  subCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  subCardTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  subCardTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#0F172A",
  },
  subCardSubtitle: {
    fontSize: 11,
    color: "#64748B",
    marginBottom: 12,
  },
  addLoanBtn: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: BrandColors.PRIMARY_ORANGE || "#FF7A00",
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: BrandColors.WHITE,
  },
  addLoanBtnText: {
    fontSize: 11,
    fontWeight: "700",
    color: BrandColors.PRIMARY_ORANGE || "#FF7A00",
  },
  loanFormGrid: {
    gap: 10,
  },
  gridRow: {
    flexDirection: "row",
    gap: 10,
  },
  gridCol: {
    flex: 1,
  },
  fieldLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: "#334155",
    marginBottom: 4,
  },
  errorText: {
    fontSize: 11,
    color: "#EF4444",
    marginTop: 4,
  },
  subInput: {
    backgroundColor: BrandColors.WHITE,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 12,
    color: "#0F172A",
  },
  removeLoanBtn: {
    alignSelf: "flex-end",
    marginTop: 6,
  },
  removeLoanText: {
    fontSize: 11,
    color: "#EF4444",
    fontWeight: "600",
  },
  // Modal Picker Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.4)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: Spacing.base,
    paddingBottom: Spacing.xl,
    paddingHorizontal: Spacing.base,
    maxHeight: "75%",
  },
  modalHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: Spacing.sm,
    paddingBottom: Spacing.xs,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  modalTitle: {
    fontSize: Typography.fontSize.base,
    fontWeight: Typography.fontWeight.bold,
    color: "#0F172A",
  },
  optionItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F8FAFC",
  },
  optionItemActive: {
    backgroundColor: "#FEF0E6",
    paddingHorizontal: 8,
    borderRadius: BorderRadius.sm,
  },
  optionText: {
    fontSize: Typography.fontSize.sm,
    color: "#334155",
  },
  optionTextActive: {
    color: BrandColors.PRIMARY_ORANGE_DARK || "#EA580C",
    fontWeight: Typography.fontWeight.bold,
  },
});
