import { StyleSheet } from "react-native";
import { Typography, BorderRadius } from "@/shared/theme";

export const styles = StyleSheet.create({
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1.2,
    borderColor: "#E2E8F0",
    padding: 14,
    marginBottom: 12,
  },
  cardUploaded: {
    backgroundColor: "#F0FDF4",
    borderColor: "#BBF7D0",
  },
  cardError: {
    borderColor: "#FECACA",
    backgroundColor: "#FFF5F5",
  },
  cardMainRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  iconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#EFF6FF",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  iconBoxUploaded: {
    backgroundColor: "#DCFCE7",
  },
  textColumn: {
    flex: 1,
    justifyContent: "center",
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
  },
  titleText: {
    fontSize: Typography.fontSize.sm + 1.5,
    fontWeight: "700",
    color: "#0F172A",
  },
  requiredStar: {
    fontSize: Typography.fontSize.sm + 1.5,
    fontWeight: "700",
    color: "#DC2626",
    marginLeft: 3,
  },
  subtitleText: {
    fontSize: Typography.fontSize.xs + 1.5,
    color: "#64748B",
    marginTop: 2,
    lineHeight: 17,
  },
  dropdownBtn: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 3,
    gap: 4,
  },
  dropdownText: {
    fontSize: Typography.fontSize.xs + 1.5,
    color: "#083B75",
    fontWeight: "600",
  },
  uploadPillBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: "#EEF2FF",
    borderWidth: 1,
    borderColor: "#C7D2FE",
    gap: 5,
    marginLeft: 8,
  },
  uploadPillBtnText: {
    fontSize: Typography.fontSize.xs + 1.5,
    fontWeight: "700",
    color: "#4338CA",
  },
  uploadedFileInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 6,
    gap: 6,
  },
  checkCircle: {
    marginRight: 2,
  },
  uploadedFileName: {
    fontSize: Typography.fontSize.xs + 1.5,
    fontWeight: "600",
    color: "#065F46",
    flex: 1,
  },
  uploadedActionsRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#DCFCE7",
    gap: 8,
  },
  viewButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#BFDBFE",
    backgroundColor: "#EFF6FF",
    gap: 4,
  },
  viewButtonText: {
    fontSize: Typography.fontSize.xs + 1.5,
    fontWeight: "700",
    color: "#1E40AF",
  },
  changeButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#FED7AA",
    backgroundColor: "#FFF7ED",
    gap: 4,
  },
  changeButtonText: {
    fontSize: Typography.fontSize.xs + 1.5,
    fontWeight: "700",
    color: "#C2410C",
  },
  deleteButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#FECACA",
    backgroundColor: "#FEF2F2",
    justifyContent: "center",
    alignItems: "center",
  },
  errorRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    gap: 6,
    backgroundColor: "#FEF2F2",
    padding: 8,
    borderRadius: BorderRadius.sm,
  },
  errorText: {
    fontSize: Typography.fontSize.xs + 1,
    color: "#DC2626",
    fontWeight: "500",
    flex: 1,
  },
  busyOverlay: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 4,
  },
  busyText: {
    fontSize: Typography.fontSize.xs + 1.5,
    color: "#083B75",
    fontWeight: "600",
  },
});
