import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  card: {
    backgroundColor: "#F0FDF4",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#DCFCE7",
    paddingVertical: 20,
    paddingHorizontal: 16,
    alignItems: "center",
    marginTop: 14,
    marginBottom: 14,
  },
  celebrationWrapper: {
    width: 120,
    height: 68,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  confettiSvg: {
    position: "absolute",
    top: 0,
    left: 0,
  },
  outerCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#16A34A",
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    fontSize: 19,
    fontWeight: "800",
    color: "#0B1F3A",
    textAlign: "center",
    marginTop: 10,
    letterSpacing: -0.2,
  },
  subtitle: {
    fontSize: 12,
    color: "#64748B",
    textAlign: "center",
    lineHeight: 16.5,
    marginTop: 4,
    paddingHorizontal: 6,
    fontWeight: "400",
  },
  idCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#D1FAE5",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 7,
    marginTop: 14,
  },
  idLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#0B1F3A",
  },
  idValue: {
    fontSize: 13,
    fontWeight: "800",
    color: "#16A34A",
    letterSpacing: 0.2,
  },
});
