import { CertificateDetails } from "../types/gstCertificateTypes";

export const buildCertificateHtml = (d: CertificateDetails): string => `<!DOCTYPE html><html><head><meta charset="utf-8"/><style>
@page{size:A4 portrait;margin:8mm}body{font-family:Arial,Helvetica,sans-serif;color:#0F172A;margin:0;padding:6px;font-size:10.5px}
.box{border:2px solid #1E5EFF;padding:6px}.in-box{border:1px solid #1E5EFF;padding:8px}.hdr{text-align:center;margin-bottom:6px}
.banner{background:#FFF7ED;border:1px dashed #FF7A00;color:#FF7A00;text-align:center;padding:5px;font-size:9.5px;font-weight:800;letter-spacing:0.8px;margin-bottom:6px}
.h1{font-size:12.5px;font-weight:800;color:#1E5EFF;letter-spacing:1px}.h2{font-size:9.5px;font-weight:700;color:#334155;margin:2px 0}
.title{font-size:15px;font-weight:900;color:#1E5EFF;margin:3px 0}.sub{font-size:9.5px;color:#475569}.tbl{width:100%;border-collapse:collapse;margin:5px 0;page-break-inside:avoid}
td,th{border:1px solid #CBD5E1;padding:4px 6px;font-size:10px;vertical-align:top;word-break:break-word}.lbl{width:33%;background:#F8FAFC;font-weight:700;color:#1E293B}
.sec-hdr{background:#EFF6FF;color:#1E5EFF;font-weight:800;font-size:10px}.ftr-bar{background:#1E5EFF;color:#FFF;text-align:center;padding:4px;font-size:9px;font-weight:700;margin-top:6px}
.bot-note{display:flex;justify-content:space-between;font-size:8px;color:#64748B;margin-top:3px}.badge{border:1px solid #1E5EFF;padding:4px 8px;border-radius:4px;font-size:8.5px;color:#1E5EFF;text-align:left}
</style></head><body><div class="box"><div class="in-box">
<div class="banner">SAMPLE / NOT A GOVERNMENT CERTIFICATE • TAXEDGE DEMO COPY</div>
<div style="display:flex;justify-content:space-between;align-items:flex-start"><div style="font-size:8.5px;font-weight:700;color:#64748B">FORM GST REG-06</div>
<div class="hdr" style="flex:1"><div class="h1">GOVERNMENT OF INDIA</div><div class="h2">MINISTRY OF FINANCE • GOODS AND SERVICES TAX</div>
<div class="title">CERTIFICATE OF REGISTRATION</div><div class="sub">[See Rule 10(1) of the CGST Rules, 2017]</div>
<div style="font-size:8px;color:#FF7A00;font-weight:700;margin-top:1px">TaxEdge Demo / Digitally Generated Copy</div></div>
<div style="text-align:right"><span style="font-size:14px;font-weight:900;color:#1E5EFF">GST</span><div style="font-size:7.5px;color:#64748B">1/1</div></div></div>
<table class="tbl">
<tr><td style="width:5%">1.</td><td class="lbl">GSTIN</td><td style="font-weight:800;color:#1E5EFF">${d.gstin}</td></tr><tr><td>2.</td><td class="lbl">Legal Name of Business</td><td style="font-weight:700">${d.legalName}</td></tr>
<tr><td>3.</td><td class="lbl">Trade Name, if any</td><td>${d.tradeName}</td></tr><tr><td>4.</td><td class="lbl">Constitution of Business</td><td>${d.constitution}</td></tr>
<tr><td>5.</td><td class="lbl">Address of Principal Place of Business</td><td>${d.address}</td></tr><tr><td>6.</td><td class="lbl">Date of Liability</td><td>${d.liabilityDate || "Applicable under Act"}</td></tr>
<tr><td>7.</td><td class="lbl">Period of Validity</td><td>From ${d.validityFrom || "Registration Date"} To -----------</td></tr><tr><td>8.</td><td class="lbl">Type of Registration</td><td>${d.regType}</td></tr>
<tr><td>9.</td><td class="lbl">Date of Registration</td><td>${d.regDate}</td></tr><tr><td>10.</td><td class="lbl">Date of Issue of Certificate</td><td>${d.issueDate}</td></tr>
</table>
${d.additionalPlaces?.length ? `<table class="tbl"><tr class="sec-hdr"><th colspan="2">Details of Additional Places of Business</th></tr><tr><th style="width:10%">Sl. No.</th><th>Address</th></tr>${d.additionalPlaces.map((a: string, i: number) => `<tr><td>${i + 1}.</td><td>${a}</td></tr>`).join("")}</table>` : ""}
${d.signatories?.length ? `<table class="tbl"><tr class="sec-hdr"><th colspan="3">Details of Proprietor / Partners / Directors / Promoters</th></tr><tr><th style="width:10%">Sl. No.</th><th>Name</th><th>Designation</th></tr>${d.signatories.map((s, i: number) => `<tr><td>${i + 1}.</td><td style="font-weight:700">${s.name}</td><td>${s.designation}</td></tr>`).join("")}</table>` : ""}
${d.activities?.length ? `<table class="tbl"><tr class="sec-hdr"><th colspan="2">Nature of Business Activities</th></tr><tr>${d.activities.map((act: string, i: number) => `<td>${i + 1}. ${act}</td>`).join("")}</tr></table>` : ""}
<div style="display:flex;justify-content:space-between;align-items:center;margin-top:6px">
<div class="badge"><b style="color:#1E5EFF">TaxEdge Certificate Information</b><br>GSTIN: ${d.gstin}<br>Certificate Type: Form GST REG-06<br>Generated: ${d.issueDate}<br>Status: Digitally Generated Demo Copy</div>
<div style="width:55%;border:1px dashed #CBD5E1;padding:6px;font-size:8.5px;color:#475569;text-align:center">This document is generated by TaxEdge for demonstration purposes and is not an official government-issued certificate.</div>
</div>
<div class="ftr-bar">TAXEDGE • DIGITALLY GENERATED DEMO CERTIFICATE</div>
<div class="bot-note"><span>TaxEdge Demo Copy • Not a Government Document</span><span>Form GST REG-06 Reference</span></div>
</div></div></body></html>`;
