package com.taxedge.gst.enums;

public enum GstFilingDocumentType {

    SALES_INVOICE,
    PURCHASE_INVOICES,
    GSTR_2B_ITC_STATEMENT,
    CREDIT_NOTES,
    DEBIT_NOTES,
    E_INVOICE_DATA,
    E_WAY_BILL_DATA,
    EXPENSE_INVOICES_AND_VOUCHERS,
    BANK_STATEMENT,
    PREVIOUS_GST_RETURNS,
    PREVIOUS_FILING_ACKNOWLEDGEMENT,
    OTHER_SUPPORTING_DOCUMENTS
}