package com.taxedge.loan.homeloan.enums;

public enum PropertyIntent {
    NEW_APARTMENT_FLAT_PURCHASE,
    HOUSE_CONSTRUCTION_SELF_BUILD,
    RESALE_PROPERTY_PURCHASE,
    PLOT_PURCHASE_CONSTRUCTION,
    HOME_RENOVATION_EXTENSION,
    BALANCE_TRANSFER_TAKEOVER,
    TOP_UP_EXISTING_HOME_LOAN,
    OTHERS
}
