import { StyleSheet } from "react-native";
import { BrandColors, Typography, Spacing, BorderRadius } from "@/shared/theme";

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(11, 31, 58, 0.6)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: BorderRadius.lg,
    borderTopRightRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.base,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.xxl,
    maxHeight: "85%",
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: Spacing.xs,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
  },
  headerTitle: {
    fontSize: Typography.fontSize.lg,
    fontWeight: Typography.fontWeight.bold,
    color: "#0F172A",
  },
  closeBtn: {
    padding: Spacing.xs,
  },
  subtitle: {
    fontSize: Typography.fontSize.xs,
    color: "#64748B",
    lineHeight: 18,
    marginBottom: Spacing.md,
  },
  bankList: {
    gap: Spacing.sm,
    marginBottom: Spacing.base,
  },
  bankCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
  },
  bankCardSelected: {
    borderColor: BrandColors.PRIMARY_ORANGE,
    backgroundColor: "#FFFBF7",
  },
  bankInfoCol: {
    flex: 1,
    gap: 2,
  },
  bankTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
  },
  bankName: {
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.bold,
    color: "#0F172A",
  },
  validatedTag: {
    backgroundColor: "#DCFCE7",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  validatedTagText: {
    fontSize: 10,
    fontWeight: Typography.fontWeight.bold,
    color: "#166534",
  },
  bankNumber: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.semiBold,
    color: "#334155",
    letterSpacing: 0.5,
  },
  bankSub: {
    fontSize: 11,
    color: "#64748B",
  },
  radioCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#CBD5E1",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: Spacing.sm,
  },
  radioCircleSelected: {
    borderColor: BrandColors.PRIMARY_ORANGE,
  },
  radioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: BrandColors.PRIMARY_ORANGE,
  },
  addBankBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: Spacing.sm,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: BorderRadius.sm,
    borderStyle: "dashed",
    marginBottom: Spacing.md,
  },
  addBankBtnText: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.semiBold,
    color: "#083B75",
  },
  addFormContainer: {
    backgroundColor: "#F8FAFC",
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: Spacing.md,
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  inputGroup: {
    gap: 4,
  },
  inputLabel: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.semiBold,
    color: "#334155",
  },
  inputBox: {
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    paddingHorizontal: Spacing.sm,
    height: 42,
    justifyContent: "center",
  },
  textInput: {
    fontSize: Typography.fontSize.xs,
    color: "#0F172A",
  },
  saveBankBtn: {
    backgroundColor: BrandColors.PRIMARY_BLUE,
    paddingVertical: 10,
    borderRadius: BorderRadius.sm,
    alignItems: "center",
    marginTop: Spacing.xs,
  },
  saveBankBtnText: {
    color: "#FFFFFF",
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.bold,
  },
  confirmBtn: {
    backgroundColor: BrandColors.PRIMARY_ORANGE,
    paddingVertical: 12,
    borderRadius: BorderRadius.md,
    alignItems: "center",
    justifyContent: "center",
  },
  confirmBtnText: {
    color: "#FFFFFF",
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.bold,
  },
});
