import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    alignItems: "center",
    paddingTop: 10,
    paddingBottom: 6,
  },
  badgeWrapper: {
    alignItems: "center",
    justifyContent: "center",
    height: 90,
    width: 140,
    position: "relative",
  },
  confettiSvg: {
    position: "absolute",
    top: 0,
    left: 0,
  },
  successOuterCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#E8F8EE",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#DCFCE7",
  },
  successInnerCircle: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "#DCFCE7",
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    fontSize: 21,
    fontWeight: "800",
    color: "#0B1F3A",
    textAlign: "center",
    letterSpacing: -0.3,
    marginTop: 12,
    paddingHorizontal: 16,
  },
  subtitle: {
    fontSize: 13,
    color: "#64748B",
    textAlign: "center",
    lineHeight: 18,
    marginTop: 6,
    paddingHorizontal: 24,
    fontWeight: "400",
  },
  idCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ECFDF5",
    borderWidth: 1,
    borderColor: "#D1FAE5",
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 7,
    marginTop: 14,
  },
  idLabel: {
    fontSize: 12.5,
    fontWeight: "600",
    color: "#0B1F3A",
  },
  idValue: {
    fontSize: 13,
    fontWeight: "800",
    color: "#16A34A",
    letterSpacing: 0.3,
  },
});
