import { StyleSheet, Platform, ViewStyle } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0B1F3A",
    justifyContent: "space-between",
    paddingHorizontal: 20,
  },
  centerSection: {
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  celebrationContainer: {
    alignItems: "center",
    justifyContent: "center",
    height: 160,
    width: 220,
    position: "relative",
    marginBottom: 10,
  },
  confettiSvg: {
    position: "absolute",
    top: 0,
    left: 0,
  },
  pulseOuterCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "rgba(249, 115, 22, 0.15)",
    justifyContent: "center",
    alignItems: "center",
  },
  pulseMiddleCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "rgba(249, 115, 22, 0.3)",
    justifyContent: "center",
    alignItems: "center",
  },
  orangeCoreCircle: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: "#F97316",
    justifyContent: "center",
    alignItems: "center",
    ...Platform.select({
      ios: {
        shadowColor: "#F97316",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.5,
        shadowRadius: 16,
      },
      android: {
        elevation: 8,
      },
      default: {},
    }),
  },
  verifiedHeading: {
    fontSize: 22,
    fontWeight: "900",
    color: "#F97316",
    letterSpacing: 0.5,
    textAlign: "center",
    marginTop: 10,
  },
  verifiedSub: {
    fontSize: 13,
    color: "#CBD5E1",
    textAlign: "center",
    lineHeight: 18,
    marginTop: 8,
    paddingHorizontal: 16,
    fontWeight: "400",
  },
  metadataCard: {
    width: "100%",
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
    marginTop: 24,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 6,
  },
  metaDivider: {
    height: 1,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    marginVertical: 4,
  },
  metaLabel: {
    fontSize: 12.5,
    color: "#94A3B8",
    fontWeight: "500",
  },
  metaValue: {
    fontSize: 13,
    color: "#FFFFFF",
    fontWeight: "700",
  },
  statusPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(22, 163, 74, 0.2)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
  },
  statusText: {
    fontSize: 11.5,
    color: "#4ADE80",
    fontWeight: "700",
  },
  bottomButtonsContainer: {
    width: "100%",
    gap: 10,
  },
  primaryOrangeButton: {
    height: 52,
    borderRadius: 14,
    backgroundColor: "#F97316",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    ...Platform.select({
      ios: {
        shadowColor: "#F97316",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.35,
        shadowRadius: 10,
      },
      android: {
        elevation: 4,
      },
      default: {},
    }),
  },
  primaryButtonText: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0B1F3A",
    letterSpacing: 0.2,
  },
  secondaryNavyButton: {
    height: 48,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.3)",
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
  },
  secondaryButtonText: {
    fontSize: 14.5,
    fontWeight: "700",
    color: "#CBD5E1",
  },
});

export const getContainerInsetsStyle = (topInset: number, bottomInset: number): ViewStyle => ({
  paddingTop: topInset,
  paddingBottom: bottomInset + 20,
});
