import { StyleSheet } from "react-native";
import { BrandColors, Typography } from "../../../../../shared/theme";

export const styles = StyleSheet.create({
  container: {
    paddingBottom: 24,
  },
  sectionTitle: {
    fontSize: Typography.fontSize.lg,
    fontWeight: "700",
    color: "#0F172A",
    marginBottom: 4,
  },
  sectionSubtitle: {
    fontSize: Typography.fontSize.sm,
    color: "#64748B",
    marginBottom: 16,
  },
  progressContainer: {
    backgroundColor: BrandColors.WHITE,
    borderRadius: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginBottom: 16,
  },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  progressTitle: {
    fontSize: Typography.fontSize.sm,
    fontWeight: "600",
    color: "#1E293B",
  },
  progressCount: {
    fontSize: Typography.fontSize.sm,
    fontWeight: "700",
    color: BrandColors.PRIMARY_BLUE,
  },
  progressBarTrack: {
    height: 6,
    backgroundColor: "#E2E8F0",
    borderRadius: 3,
    overflow: "hidden",
  },
  categoryContainer: {
    marginBottom: 18,
  },
  categoryHeader: {
    fontSize: Typography.fontSize.sm,
    fontWeight: "700",
    color: "#475569",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 8,
    marginLeft: 2,
  },
  docCard: {
    backgroundColor: BrandColors.WHITE,
    borderRadius: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  docCardUploaded: {
    borderColor: "#86EFAC",
    backgroundColor: "#F0FDF4",
  },
  docLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    marginRight: 8,
  },
  iconBox: {
    width: 40,
    height: 40,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  docInfo: {
    flex: 1,
  },
  docNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    flexWrap: "wrap",
  },
  docName: {
    fontSize: Typography.fontSize.sm,
    fontWeight: "600",
    color: "#0F172A",
  },
  starText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#EF4444",
  },
  docSubtitle: {
    fontSize: Typography.fontSize.xs,
    color: "#64748B",
    marginTop: 2,
  },
  fileMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 4,
  },
  fileNameText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#15803D",
    maxWidth: 130,
  },
  fileSizeText: {
    fontSize: 10,
    color: "#64748B",
  },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  viewButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EFF6FF",
    borderWidth: 1,
    borderColor: "#3B82F6",
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 6,
    gap: 3,
  },
  viewButtonText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#2563EB",
  },
  deleteButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FEE2E2",
    borderWidth: 1,
    borderColor: "#EF4444",
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 6,
    gap: 3,
  },
  deleteButtonText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#DC2626",
  },
  uploadButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF7ED",
    borderWidth: 1,
    borderColor: BrandColors.PRIMARY_ORANGE,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 6,
    gap: 4,
  },
  uploadButtonText: {
    fontSize: Typography.fontSize.xs,
    fontWeight: "600",
    color: BrandColors.PRIMARY_ORANGE,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "flex-end",
  },
  sheetContent: {
    backgroundColor: BrandColors.WHITE,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 36,
  },
  sheetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sheetTitle: {
    fontSize: Typography.fontSize.base,
    fontWeight: "700",
    color: "#0F172A",
  },
  sheetOption: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
    gap: 12,
  },
  sheetOptionText: {
    fontSize: Typography.fontSize.sm,
    fontWeight: "600",
    color: "#1E293B",
  },
  previewCard: {
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 16,
  },
  previewFileName: {
    fontSize: 14,
    fontWeight: "700",
    color: "#0F2052",
    marginTop: 8,
  },
  previewFileSize: {
    fontSize: 12,
    color: "#64748B",
    marginTop: 2,
  },
});
