import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingVertical: 13,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 11,
    ...Platform.select({
      ios: {
        shadowColor: "#0B1F3A",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.02,
        shadowRadius: 4,
      },
      android: {
        elevation: 1,
      },
      default: {},
    }),
  },
  leftGroup: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    marginRight: 10,
  },
  textGroup: {
    marginLeft: 12,
    flex: 1,
  },
  docTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#0B1F3A",
    letterSpacing: -0.1,
  },
  docSubtitle: {
    fontSize: 11.5,
    color: "#64748B",
    marginTop: 2.5,
    fontWeight: "500",
  },
  uploadButton: {
    borderWidth: 1.5,
    borderColor: "#F97316",
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 7,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#FFFFFF",
  },
  uploadButtonText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#F97316",
  },
  uploadedBadge: {
    borderWidth: 1.5,
    borderColor: "#F97316",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#FFF7ED",
  },
  uploadedText: {
    fontSize: 12.5,
    fontWeight: "700",
    color: "#F97316",
  },
  verifiedBadge: {
    backgroundColor: "#0B1F3A",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  verifiedText: {
    fontSize: 12.5,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  underReviewBadge: {
    backgroundColor: "#EAF1FE",
    borderWidth: 1,
    borderColor: "#0B1F3A",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  underReviewText: {
    fontSize: 12.5,
    fontWeight: "700",
    color: "#0B1F3A",
  },
  rejectedButton: {
    borderWidth: 1.5,
    borderColor: "#DC2626",
    backgroundColor: "#FEF2F2",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  rejectedText: {
    fontSize: 12.5,
    fontWeight: "700",
    color: "#DC2626",
  },
});
