import { StyleSheet, type Insets } from "react-native";
import { BrandColors, Typography, Spacing, BorderRadius } from "../../../../shared/theme";

export const previewModalColors = {
  documentIcon: BrandColors.PRIMARY_ORANGE,
  closeIcon: BrandColors.TEXT_SECONDARY,
  verifiedIcon: "#166534",
  shareIcon: BrandColors.PRIMARY_ORANGE_DARK,
} as const;

export const closeButtonHitSlop: Insets = { top: 10, bottom: 10, left: 10, right: 10 };

export const styles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.65)",
    justifyContent: "center",
    alignItems: "center",
    padding: Spacing.base,
  },
  modalContainer: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: BrandColors.WHITE,
    borderRadius: BorderRadius.lg,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 8,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: Spacing.base,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: BrandColors.CARD_BORDER,
    backgroundColor: BrandColors.WHITE,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    flex: 1,
    marginRight: Spacing.sm,
  },
  title: {
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.bold,
    color: BrandColors.TEXT_PRIMARY,
    flex: 1,
  },
  closeBtn: {
    padding: Spacing.xs,
  },
  content: {
    padding: Spacing.base,
    alignItems: "center",
  },
  imagePreview: {
    width: "100%",
    height: 320,
    borderRadius: BorderRadius.sm,
    backgroundColor: BrandColors.BACKGROUND,
  },
  docCard: {
    width: "100%",
    alignItems: "center",
    paddingVertical: Spacing.lg,
    paddingHorizontal: Spacing.base,
    borderRadius: BorderRadius.md,
    backgroundColor: BrandColors.BACKGROUND,
    borderWidth: 1,
    borderColor: BrandColors.BORDER,
  },
  iconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: BrandColors.PRIMARY_LIGHT_ORANGE,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: Spacing.md,
  },
  fileName: {
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.bold,
    color: BrandColors.TEXT_PRIMARY,
    textAlign: "center",
    marginBottom: Spacing.xs,
  },
  fileMeta: {
    fontSize: Typography.fontSize.xs,
    color: BrandColors.TEXT_SECONDARY,
    textAlign: "center",
    marginBottom: Spacing.md,
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.md,
    backgroundColor: "#DCFCE7",
    marginBottom: Spacing.base,
  },
  statusText: {
    fontSize: Typography.fontSize.xs - 1,
    fontWeight: Typography.fontWeight.semiBold,
    color: "#166534",
  },
  shareBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: Spacing.base,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: BrandColors.PRIMARY_ORANGE,
    backgroundColor: BrandColors.WHITE,
  },
  shareBtnText: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.bold,
    color: BrandColors.PRIMARY_ORANGE_DARK,
  },
  footer: {
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.md,
    borderTopWidth: 1,
    borderTopColor: BrandColors.CARD_BORDER,
    backgroundColor: BrandColors.WHITE,
  },
  closeActionBtn: {
    width: "100%",
    paddingVertical: 11,
    borderRadius: BorderRadius.sm,
    backgroundColor: BrandColors.CARD_BORDER,
    alignItems: "center",
    justifyContent: "center",
  },
  closeActionText: {
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.semiBold,
    color: "#475569",
  },
});
