import { StyleSheet } from "react-native";
import { BrandColors, Typography, BorderRadius } from "../../../../../shared/theme";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: BorderRadius.lg || 16,
    padding: 24,
    alignItems: "center",
    width: "100%",
    maxWidth: 360,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  iconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#DCFCE7",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  title: {
    fontSize: Typography.fontSize.lg,
    fontWeight: "700",
    color: "#0F172A",
    textAlign: "center",
    marginBottom: 8,
  },
  appIdBadge: {
    backgroundColor: "#F1F5F9",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: BorderRadius.sm,
    marginBottom: 12,
  },
  appIdText: {
    fontSize: Typography.fontSize.xs,
    fontWeight: "700",
    color: "#475569",
  },
  description: {
    fontSize: Typography.fontSize.xs,
    color: "#64748B",
    textAlign: "center",
    lineHeight: 18,
    marginBottom: 20,
  },
  trackButton: {
    backgroundColor: BrandColors.PRIMARY_ORANGE || "#EA580C",
    borderRadius: BorderRadius.sm,
    paddingVertical: 14,
    paddingHorizontal: 24,
    width: "100%",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
  },
  trackButtonText: {
    color: "#FFFFFF",
    fontSize: Typography.fontSize.sm,
    fontWeight: "700",
  },
  doneButton: {
    backgroundColor: "#F1F5F9",
    borderRadius: BorderRadius.sm,
    paddingVertical: 12,
    paddingHorizontal: 24,
    width: "100%",
    alignItems: "center",
    marginTop: 10,
  },
  doneButtonText: {
    color: "#475569",
    fontSize: Typography.fontSize.sm,
    fontWeight: "600",
  },
});
